"""Telegram file_ids for onboarding media. Auto-generated by
scripts/upload_onboarding_assets.py. file_ids are bot-specific (tied to the
bot token). Re-run that script if the token changes or assets are replaced.
"""

ONBOARDING_ASSETS: dict[str, str] = {
    'step1_photo_1': 'AgACAgIAAxkDAAIZ-Gol0imMWqapxapFdGr1QNuNwB-NAAK2IGsbbk0oSUTZ8GCRpbBPAQADAgADeQADOwQ',  # photo
    'step1_photo_2': 'AgACAgIAAxkDAAIZ-Wol0irLRgABzfG3ex1yYXI3Yv9zwQACtyBrG25NKEn3zOsxK8HCrQEAAwIAA3kAAzsE',  # photo
    'step1_photo_3': 'AgACAgIAAxkDAAIZ-mol0ivYEi5pPG66Tzr12q0BUK1yAAK4IGsbbk0oSVRZFivad3gPAQADAgADeQADOwQ',  # photo
    'step2_action_button': 'BAACAgIAAxkDAAIZ-2ol0jAzGlC-kEeOT4-yzeCcmY-lAAKznwACbk0oSfzbG6YhzCefOwQ',  # video
    'step2_back_tap': 'BAACAgIAAxkDAAIZ_Gol0jgepmW2J0yTF-cQcFoHlsPVAAK0nwACbk0oSXvQCKihFAhtOwQ',  # video
    'howto_shortcut': 'BAACAgIAAxkDAAIZ_Wol0kooAu9iWwAB56e5dJY3PFIUKwACtZ8AAm5NKEl87F6PToleBzsE',  # video
    'howto_learn_words': 'BAACAgIAAxkDAAIZ_mol0lHDnZqRFt7TfRc5dlOsATFZAAK3nwACbk0oSb881M2KZj-DOwQ',  # video
    'howto_tests_quizzes': 'BAACAgIAAxkDAAIZ_2ol0lzB0YhZj2x-SbQ3i8K3Cxj3AAK4nwACbk0oSeZM7MtV0bt5OwQ',  # video
    'howto_translate_sentences': 'BAACAgIAAxkDAAIaAAFqJdJuAb_NuPK5NtcM2dwMKBi5TAACuZ8AAm5NKEldIeRXRQVkuzsE',  # video
    'howto_youtube_subs': 'BAACAgIAAxkDAAIaAWol0nwRRQEQ_J_ue9MdhQTdYKPXAAK6nwACbk0oSewpJ1-M6aZlOwQ',  # video
    'step3_photo': '',  # photo
}
