"""
German compound word (Komposita) bank for visual rebuses.
Each entry: two visual parts + wrong options sharing one component.
Component image prompts are shared across entries (cached once in DB).
"""

# DALL-E prompt per component word. Style: clean illustration, white background, single object.
_STYLE = (
    "children's book illustration style, soft watercolor, vibrant colors, "
    "clean white background, single object centered, no text, no labels, no other objects, "
    "high clarity, detailed"
)

COMPONENT_IMAGE_PROMPTS: dict[str, str] = {
    # Body parts
    "Hand":         f"An open human hand, palm facing viewer, fingers spread, {_STYLE}",
    "Fuß":          f"A single bare human foot, side view, {_STYLE}",
    "Arm":          f"A human arm, slightly bent, {_STYLE}",
    "Finger":       f"A single pointing human finger, {_STYLE}",
    "Ohr":          f"A single human ear, side profile, {_STYLE}",
    "Hals":         f"A human neck and throat area, front view, {_STYLE}",
    "Nase":         f"A human nose, front view, {_STYLE}",
    "Auge":         f"A single human eye with eyelashes, {_STYLE}",
    "Kopf":         f"A simple human head, side profile, {_STYLE}",
    "Bauch":        f"A human torso showing belly/abdomen area, {_STYLE}",
    "Rücken":       f"A human back, rear view, {_STYLE}",
    "Zahn":         f"A single large white tooth, {_STYLE}",
    "Haar":         f"A lock of flowing hair, {_STYLE}",
    # Clothing & accessories
    "Schuh":        f"A single brown leather shoe, side view, {_STYLE}",
    "Brille":       f"A pair of round eyeglasses with dark frames, {_STYLE}",
    "Tasche":       f"A small brown leather bag, {_STYLE}",
    "Tuch":         f"A folded piece of cloth/fabric, {_STYLE}",
    "Hut":          f"A classic wide-brimmed hat, {_STYLE}",
    "Ring":         f"A simple gold ring, {_STYLE}",
    "Band":         f"A decorative ribbon/band tied in a bow, {_STYLE}",
    "Kette":        f"A metal chain necklace, {_STYLE}",
    "Nagel":        f"A single metal nail, sharp and pointed, {_STYLE}",
    "Schere":       f"A pair of scissors, open, {_STYLE}",
    "Bürste":       f"A cleaning brush with bristles, {_STYLE}",
    "Wolle":        f"A ball of knitting wool/yarn, {_STYLE}",
    # Nature & weather
    "Sonne":        f"A bright yellow sun with rays, {_STYLE}",
    "Regen":        f"Raindrops falling, a rain shower, {_STYLE}",
    "Schnee":       f"A pile of white snow, {_STYLE}",
    "Mond":         f"A bright full moon, glowing, {_STYLE}",
    "Stern":        f"A single five-pointed star, glowing, {_STYLE}",
    "Wind":         f"Swirling wind lines and leaves blowing, {_STYLE}",
    "Eis":          f"A block of clear blue ice with cracks, {_STYLE}",
    "Wasser":       f"A splash of clear water, {_STYLE}",
    "Feuer":        f"Orange flames burning, {_STYLE}",
    "Erde":         f"A handful of dark brown soil/earth, {_STYLE}",
    "Sand":         f"A small pile of golden sand, {_STYLE}",
    "Licht":        f"A bright glowing light beam, {_STYLE}",
    "Schein":       f"Rays of glowing light shining outward, {_STYLE}",
    "Dampf":        f"White steam rising upward, {_STYLE}",
    "Sturm":        f"Dark storm clouds with lightning, {_STYLE}",
    "Flocke":       f"A single detailed snowflake crystal, {_STYLE}",
    "Bogen":        f"A curved arc shape, like a rainbow arch, {_STYLE}",
    "Sichel":       f"A silver crescent sickle blade, {_STYLE}",
    # Trees, plants & food
    "Baum":         f"A large deciduous tree with full canopy, {_STYLE}",
    "Tanne":        f"A green Christmas fir tree, triangular shape, {_STYLE}",
    "Blume":        f"A bright red flower with green stem, {_STYLE}",
    "Rose":         f"A single red rose with stem, {_STYLE}",
    "Apfel":        f"A shiny red apple, {_STYLE}",
    "Birne":        f"A yellow pear, {_STYLE}",
    "Kirsche":      f"Two red cherries on a stem, {_STYLE}",
    "Orange":       f"A whole orange fruit with leaf, {_STYLE}",
    "Zitrone":      f"A yellow lemon, {_STYLE}",
    "Traube":       f"A bunch of purple grapes, {_STYLE}",
    "Beere":        f"A small round berry, dark purple, {_STYLE}",
    "Heide":        f"A heath moorland landscape with purple heather, {_STYLE}",
    "Stachel":      f"A sharp thorn/spine on a branch, {_STYLE}",
    "Kohl":         f"A green cabbage head, {_STYLE}",
    "Knochen":      f"A white bone, {_STYLE}",
    "Nuss":         f"A walnut, shell cracked open, {_STYLE}",
    "Pilz":         f"A brown mushroom with white spots, {_STYLE}",
    "Stein":        f"A smooth grey stone/rock, {_STYLE}",
    "Zapfen":       f"A pine cone, {_STYLE}",
    "Eiche":        f"An oak tree, {_STYLE}",
    "Hörnchen":     f"A small croissant-shaped pastry, {_STYLE}",
    # Animals
    "Hund":         f"A sitting dog, friendly, {_STYLE}",
    "Katze":        f"A sitting cat, {_STYLE}",
    "Vogel":        f"A small bird perched, {_STYLE}",
    "Pferd":        f"A standing horse, side view, {_STYLE}",
    "Kuh":          f"A black and white dairy cow, side view, {_STYLE}",
    "Schwein":      f"A pink pig, side view, {_STYLE}",
    "Schaf":        f"A fluffy white sheep, {_STYLE}",
    "Hase":         f"A white rabbit with long ears, sitting, {_STYLE}",
    "Bär":          f"A brown bear, standing, {_STYLE}",
    "Wolf":         f"A grey wolf, {_STYLE}",
    "Tiger":        f"An orange tiger with black stripes, {_STYLE}",
    "Löwe":         f"A lion with large mane, {_STYLE}",
    "Elefant":      f"A grey elephant, side view, {_STYLE}",
    "Giraffe":      f"A giraffe with long neck, {_STYLE}",
    "Adler":        f"An eagle with wings slightly spread, {_STYLE}",
    "Fisch":        f"A colourful fish, side view, {_STYLE}",
    "Hai":          f"A shark, side view with dorsal fin, {_STYLE}",
    "Biene":        f"A yellow and black bee, {_STYLE}",
    "Huhn":         f"A hen/chicken, side view, {_STYLE}",
    "Hahn":         f"A rooster with red comb, {_STYLE}",
    "Tinte":        f"An ink bottle with blue ink, {_STYLE}",
    "Rüssel":       f"An elephant trunk curled, {_STYLE}",
    "Mähne":        f"A flowing lion mane, {_STYLE}",
    "Fell":         f"A piece of animal fur/pelt, {_STYLE}",
    "Schwanz":      f"An animal tail, curled, {_STYLE}",
    "Flügel":       f"A bird wing, outstretched, {_STYLE}",
    "Kamm":         f"A hair comb with fine teeth, {_STYLE}",
    "Horn":         f"A single animal horn or musical horn, curved, {_STYLE}",
    "Spiel":        f"Colourful board game pieces and dice on a table, {_STYLE}",
    "Klaue":        f"An animal claw, {_STYLE}",
    "Schnabel":     f"A duck beak, side view, {_STYLE}",
    # Objects & household
    "Haus":         f"A small house with red roof, {_STYLE}",
    "Tür":          f"A wooden door with handle, {_STYLE}",
    "Fenster":      f"A window with frame, {_STYLE}",
    "Topf":         f"A ceramic flower pot, terracotta, {_STYLE}",
    "Kasten":       f"A wooden box/crate, {_STYLE}",
    "Korb":         f"A woven wicker basket, {_STYLE}",
    "Käfig":        f"A bird cage, wire bars, {_STYLE}",
    "Regal":        f"A wooden bookshelf with shelves, {_STYLE}",
    "Tisch":        f"A simple wooden table, {_STYLE}",
    "Stuhl":        f"A simple wooden chair, {_STYLE}",
    "Lampe":        f"A table lamp with shade, {_STYLE}",
    "Schirm":       f"An open umbrella, {_STYLE}",
    "Schloss":      f"A padlock, closed, {_STYLE}",
    "Schlüssel":    f"A single golden key, {_STYLE}",
    "Loch":         f"A round hole in a white surface, {_STYLE}",
    "Messer":       f"A kitchen knife, blade visible, {_STYLE}",
    "Glas":         f"An empty clear drinking glass, {_STYLE}",
    "Tasse":        f"A white ceramic tea cup with saucer, {_STYLE}",
    "Teller":       f"A round white plate, {_STYLE}",
    "Schüssel":     f"A ceramic bowl, {_STYLE}",
    "Kelle":        f"A soup ladle, {_STYLE}",
    "Pfanne":       f"A frying pan, {_STYLE}",
    "Turm":         f"A tall stone tower, {_STYLE}",
    "Wagen":        f"A small wooden cart with wheels, {_STYLE}",
    "Ball":         f"A colourful rubber ball, {_STYLE}",
    "Würfel":       f"A single white dice cube, {_STYLE}",
    "Uhr":          f"A classic round clock showing 12 o'clock, {_STYLE}",
    "Bett":         f"A bed with pillow and duvet, {_STYLE}",
    "Decke":        f"A folded blanket/duvet, {_STYLE}",
    "Kissen":       f"A fluffy white pillow, {_STYLE}",
    "Spiegel":      f"A round mirror with reflection, {_STYLE}",
    "Buch":         f"A single closed book, {_STYLE}",
    "Bücher":       f"A stack of colourful books, {_STYLE}",
    "Brief":        f"A white envelope with letter, {_STYLE}",
    "Schrank":      f"A wooden wardrobe cabinet, {_STYLE}",
    "Maschine":     f"A mechanical gear/machine component, metallic, {_STYLE}",
    "Puppe":        f"A classic rag doll, {_STYLE}",
    "Zeug":         f"A collection of small colourful toys and objects, {_STYLE}",
    "Pasta":        f"A tube of toothpaste squeezed, {_STYLE}",
    # Outdoors & transport
    "Boot":         f"A small wooden rowing boat, {_STYLE}",
    "Schiff":       f"A sailing ship with white sails, {_STYLE}",
    "Segel":        f"A white sail billowing in wind, {_STYLE}",
    "Bahn":         f"A railway train on tracks, {_STYLE}",
    "Hafen":        f"A harbour with dock and water, {_STYLE}",
    "Flug":         f"A small aeroplane in flight, {_STYLE}",
    "Hof":          f"A farm courtyard with fence, {_STYLE}",
    "Park":         f"A park with green grass and bench, {_STYLE}",
    "Strand":       f"A sandy beach with waves, {_STYLE}",
    "Berg":         f"A snow-capped mountain peak, {_STYLE}",
    "Wald":         f"A dense green forest, {_STYLE}",
    "Fall":         f"A person or object falling downward, motion blur, {_STYLE}",
    "Brand":        f"Flames burning in a forest, {_STYLE}",
    "Rakete":       f"A rocket launching with fire trail, {_STYLE}",
    "Stall":        f"A wooden animal barn/stable, {_STYLE}",
    "Rute":         f"A plain thin straight wooden rod or switch, bare stick with no fishing equipment, {_STYLE}",
    "Angel":        f"A fishing hook with dangling line, metallic hook, no rod, {_STYLE}",
    "Hammer":       f"A metal claw hammer, {_STYLE}",
    "Schwert":      f"A shining medieval sword, {_STYLE}",
    "Pfeil":        f"A wooden arrow with feather tail, {_STYLE}",
    "Schrauber":    f"A screwdriver, metallic, {_STYLE}",
    # Food
    "Brot":         f"A round loaf of bread, {_STYLE}",
    "Suppe":        f"A bowl of steaming soup, {_STYLE}",
    "Kuchen":       f"A slice of layered cake, {_STYLE}",
    "Wein":         f"A glass of red wine, {_STYLE}",
    "Kaffee":       f"A cup of black coffee with steam, {_STYLE}",
    "Obst":         f"An assortment of fresh fruits in a pile, {_STYLE}",
    "Salat":        f"A bowl of green salad, {_STYLE}",
    "Fleisch":      f"A raw red meat steak, {_STYLE}",
    "Butter":       f"A block of yellow butter on a plate, {_STYLE}",
    "Saft":         f"A glass of orange juice, {_STYLE}",
    "Honig":        f"A jar of golden honey with a honey dipper, {_STYLE}",
    "Zucker":       f"A bowl of white granulated sugar, {_STYLE}",
    "Torte":        f"A whole decorated cream cake, {_STYLE}",
    "Schokolade":   f"A chocolate bar, broken pieces, {_STYLE}",
    "Kartoffel":    f"Several brown potatoes, {_STYLE}",
    "Brei":         f"A bowl of creamy mash, smooth texture, {_STYLE}",
    "Zwiebel":      f"A whole brown onion, {_STYLE}",
    "Korken":       f"A wine cork, cylindrical, {_STYLE}",
    "Erdnuss":      f"Several peanuts in shells, {_STYLE}",
    "Silber":       f"A polished silver bar/ingot, {_STYLE}",
    "Löffel":       f"A silver spoon, {_STYLE}",
    # Abstract/action (visualisable)
    "Schreiben":    f"A hand writing with a pen on paper, {_STYLE}",
    "Waschen":      f"Two hands being washed under water with soap, {_STYLE}",
    "Nähen":        f"A needle and thread, {_STYLE}",
    "Schlafen":     f"A person sleeping in bed, eyes closed, {_STYLE}",
    "Fahren":       f"A car moving forward on a road, {_STYLE}",
    "Kochen":       f"A pot on a stove with steam rising, {_STYLE}",
    "Hüpfen":       f"A person jumping/hopping in the air, {_STYLE}",
    "Spülen":       f"Dishes being washed under running water, {_STYLE}",
    "Braten":       f"Meat sizzling in a pan, {_STYLE}",
    "Glühen":       f"A glowing orange ember, radiant heat, {_STYLE}",
    "Rollen":       f"A wheel rolling forward, motion lines, {_STYLE}",
    "Schaukeln":    f"A garden swing swinging, {_STYLE}",
    "Liegen":       f"A person lying down flat, {_STYLE}",
    "Klingeln":     f"A doorbell with sound waves, {_STYLE}",
    "Laufen":       f"A person running in motion, {_STYLE}",
    "Schmerzen":    f"A hand clutching an area in pain, red glow, {_STYLE}",
    # Misc
    "Mann":         f"A simple silhouette of a man standing, {_STYLE}",
    "Kind":         f"A small child standing, {_STYLE}",
    "Tier":         f"Several different animals together, {_STYLE}",
    "Geld":         f"A stack of coins and banknotes, {_STYLE}",
    "Gold":         f"Shiny gold nuggets, {_STYLE}",
    "Meer":         f"Ocean waves, blue sea, {_STYLE}",
    "Himmel":       f"A blue sky with white clouds, {_STYLE}",
    "Welt":         f"A globe of the Earth, {_STYLE}",
    "Werk":         f"Colourful fireworks exploding in the sky, {_STYLE}",
    "Mühle":        f"A traditional windmill, {_STYLE}",
    "Stock":        f"A wooden walking stick/rod, {_STYLE}",
    "Wabe":         f"A hexagonal honeycomb section, {_STYLE}",
    "Früchte":      f"Several tropical fruits mixed, {_STYLE}",
    "Anzug":        f"A formal business suit on a hanger, {_STYLE}",
    "Torte_kirsch": f"A Black Forest cherry cream cake, {_STYLE}",
    "Gans":         f"A white goose, side view, {_STYLE}",
    "Haut":         f"A close-up of human skin texture on an arm, {_STYLE}",
    "Jammer":       f"A crying/wailing cat, {_STYLE}",
    "Burg":         f"A medieval castle, {_STYLE}",
    "Reise":        f"A packed travel suitcase, {_STYLE}",
    "Kuckuck":      f"A cuckoo bird, beak open calling, {_STYLE}",
    "Scheuche":     f"A scarecrow in a field, {_STYLE}",
    "Kranke":       f"A person in a hospital bed, {_STYLE}",
}

# ---------------------------------------------------------------------------
# Compound word bank
# ---------------------------------------------------------------------------
# Fields:
#   id            – unique slug
#   compound      – the full German word
#   article       – der/die/das
#   meaning_ru    – Russian translation
#   difficulty    – A2 / B1 / B2
#   category      – thematic group
#   parts         – list of exactly 2 dicts {word, meaning_ru}
#                   'word' must be a key in COMPONENT_IMAGE_PROMPTS
#   wrong_options – list of 3 real German words (share ≥1 component with compound)
#   explanation_ru – 1-sentence explanation shown after answer

REBUS_COMPOUND_BANK: list[dict] = [
    # ── A2 ──────────────────────────────────────────────────────────────────
    {
        "id": "handschuh_001",
        "compound": "Handschuh",
        "article": "der",
        "meaning_ru": "перчатка",
        "difficulty": "A2",
        "category": "clothing",
        "parts": [{"word": "Hand", "meaning_ru": "рука"}, {"word": "Schuh", "meaning_ru": "ботинок"}],
        "wrong_options": ["Hausschuh", "Handtuch", "Handtasche"],
        "explanation_ru": "Hand (рука) + Schuh (ботинок) = Handschuh — буквально «ручной ботинок»",
    },
    {
        "id": "apfelbaum_001",
        "compound": "Apfelbaum",
        "article": "der",
        "meaning_ru": "яблоня",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Apfel", "meaning_ru": "яблоко"}, {"word": "Baum", "meaning_ru": "дерево"}],
        "wrong_options": ["Birnbaum", "Apfelsaft", "Kirschbaum"],
        "explanation_ru": "Apfel (яблоко) + Baum (дерево) = Apfelbaum — яблоневое дерево",
    },
    {
        "id": "sonnenbrille_001",
        "compound": "Sonnenbrille",
        "article": "die",
        "meaning_ru": "солнечные очки",
        "difficulty": "A2",
        "category": "clothing",
        "parts": [{"word": "Sonne", "meaning_ru": "солнце"}, {"word": "Brille", "meaning_ru": "очки"}],
        "wrong_options": ["Sonnenblume", "Lesebrille", "Mondbrille"],
        "explanation_ru": "Sonne (солнце) + Brille (очки) = Sonnenbrille — солнечные очки",
    },
    {
        "id": "schluesselloch_001",
        "compound": "Schlüsselloch",
        "article": "das",
        "meaning_ru": "замочная скважина",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Schlüssel", "meaning_ru": "ключ"}, {"word": "Loch", "meaning_ru": "отверстие"}],
        "wrong_options": ["Schlüsselring", "Türloch", "Schlüsselband"],
        "explanation_ru": "Schlüssel (ключ) + Loch (дырка) = Schlüsselloch — замочная скважина",
    },
    {
        "id": "taschenlampe_001",
        "compound": "Taschenlampe",
        "article": "die",
        "meaning_ru": "фонарик",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Tasche", "meaning_ru": "карман/сумка"}, {"word": "Lampe", "meaning_ru": "лампа"}],
        "wrong_options": ["Handtasche", "Tischlampe", "Taschenrechner"],
        "explanation_ru": "Tasche (карман) + Lampe (лампа) = Taschenlampe — карманный фонарик",
    },
    {
        "id": "hundehaus_001",
        "compound": "Hundehaus",
        "article": "das",
        "meaning_ru": "собачья будка",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Hund", "meaning_ru": "собака"}, {"word": "Haus", "meaning_ru": "дом"}],
        "wrong_options": ["Vogelhaus", "Katzenhaus", "Hundebett"],
        "explanation_ru": "Hund (собака) + Haus (дом) = Hundehaus — собачья будка",
    },
    {
        "id": "fussball_001",
        "compound": "Fußball",
        "article": "der",
        "meaning_ru": "футбол / футбольный мяч",
        "difficulty": "A2",
        "category": "sport",
        "parts": [{"word": "Fuß", "meaning_ru": "нога/ступня"}, {"word": "Ball", "meaning_ru": "мяч"}],
        "wrong_options": ["Handball", "Fußweg", "Tennisball"],
        "explanation_ru": "Fuß (нога) + Ball (мяч) = Fußball — футбол, буквально «ногомяч»",
    },
    {
        "id": "blumentopf_001",
        "compound": "Blumentopf",
        "article": "der",
        "meaning_ru": "цветочный горшок",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Blume", "meaning_ru": "цветок"}, {"word": "Topf", "meaning_ru": "горшок"}],
        "wrong_options": ["Blumenstrauß", "Kochtopf", "Blumenbeet"],
        "explanation_ru": "Blume (цветок) + Topf (горшок) = Blumentopf",
    },
    {
        "id": "regenschirm_001",
        "compound": "Regenschirm",
        "article": "der",
        "meaning_ru": "зонт",
        "difficulty": "A2",
        "category": "clothing",
        "parts": [{"word": "Regen", "meaning_ru": "дождь"}, {"word": "Schirm", "meaning_ru": "экран/зонт"}],
        "wrong_options": ["Sonnenschirm", "Regenjacke", "Lampenschirm"],
        "explanation_ru": "Regen (дождь) + Schirm (экран) = Regenschirm — зонт от дождя",
    },
    {
        "id": "schneemann_001",
        "compound": "Schneemann",
        "article": "der",
        "meaning_ru": "снеговик",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Schnee", "meaning_ru": "снег"}, {"word": "Mann", "meaning_ru": "мужчина"}],
        "wrong_options": ["Schneeball", "Sandmann", "Schneeflöckchen"],
        "explanation_ru": "Schnee (снег) + Mann (человек) = Schneemann — снеговик",
    },
    {
        "id": "vogelkaefig_001",
        "compound": "Vogelkäfig",
        "article": "der",
        "meaning_ru": "птичья клетка",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Vogel", "meaning_ru": "птица"}, {"word": "Käfig", "meaning_ru": "клетка"}],
        "wrong_options": ["Vogelhaus", "Katzenkäfig", "Vogelpark"],
        "explanation_ru": "Vogel (птица) + Käfig (клетка) = Vogelkäfig",
    },
    {
        "id": "wasserfall_001",
        "compound": "Wasserfall",
        "article": "der",
        "meaning_ru": "водопад",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Wasser", "meaning_ru": "вода"}, {"word": "Fall", "meaning_ru": "падение"}],
        "wrong_options": ["Wasserball", "Steinfall", "Wasserturm"],
        "explanation_ru": "Wasser (вода) + Fall (падение) = Wasserfall — водопад",
    },
    {
        "id": "briefkasten_001",
        "compound": "Briefkasten",
        "article": "der",
        "meaning_ru": "почтовый ящик",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Brief", "meaning_ru": "письмо"}, {"word": "Kasten", "meaning_ru": "ящик"}],
        "wrong_options": ["Briefmarke", "Sandkasten", "Briefumschlag"],
        "explanation_ru": "Brief (письмо) + Kasten (ящик) = Briefkasten — почтовый ящик",
    },
    {
        "id": "eisbaer_001",
        "compound": "Eisbär",
        "article": "der",
        "meaning_ru": "белый медведь",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Eis", "meaning_ru": "лёд"}, {"word": "Bär", "meaning_ru": "медведь"}],
        "wrong_options": ["Eiszapfen", "Braunbär", "Eisfuchs"],
        "explanation_ru": "Eis (лёд) + Bär (медведь) = Eisbär — полярный медведь",
    },
    {
        "id": "armband_001",
        "compound": "Armband",
        "article": "das",
        "meaning_ru": "браслет",
        "difficulty": "A2",
        "category": "clothing",
        "parts": [{"word": "Arm", "meaning_ru": "рука/предплечье"}, {"word": "Band", "meaning_ru": "лента"}],
        "wrong_options": ["Halsband", "Armring", "Handuhr"],
        "explanation_ru": "Arm (рука) + Band (лента) = Armband — браслет",
    },
    {
        "id": "ohrring_001",
        "compound": "Ohrring",
        "article": "der",
        "meaning_ru": "серьга",
        "difficulty": "A2",
        "category": "clothing",
        "parts": [{"word": "Ohr", "meaning_ru": "ухо"}, {"word": "Ring", "meaning_ru": "кольцо"}],
        "wrong_options": ["Nasenring", "Ohrenschmerzen", "Goldring"],
        "explanation_ru": "Ohr (ухо) + Ring (кольцо) = Ohrring — серьга",
    },
    {
        "id": "halskette_001",
        "compound": "Halskette",
        "article": "die",
        "meaning_ru": "ожерелье",
        "difficulty": "A2",
        "category": "clothing",
        "parts": [{"word": "Hals", "meaning_ru": "шея"}, {"word": "Kette", "meaning_ru": "цепочка"}],
        "wrong_options": ["Handkette", "Halsband", "Armkette"],
        "explanation_ru": "Hals (шея) + Kette (цепочка) = Halskette — ожерелье",
    },
    {
        "id": "handtasche_001",
        "compound": "Handtasche",
        "article": "die",
        "meaning_ru": "сумочка",
        "difficulty": "A2",
        "category": "clothing",
        "parts": [{"word": "Hand", "meaning_ru": "рука"}, {"word": "Tasche", "meaning_ru": "сумка"}],
        "wrong_options": ["Rucksack", "Handschuh", "Schultertasche"],
        "explanation_ru": "Hand (рука) + Tasche (сумка) = Handtasche — дамская сумочка",
    },
    {
        "id": "handtuch_001",
        "compound": "Handtuch",
        "article": "das",
        "meaning_ru": "полотенце",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Hand", "meaning_ru": "рука"}, {"word": "Tuch", "meaning_ru": "ткань"}],
        "wrong_options": ["Handschuh", "Tischtuch", "Badetuch"],
        "explanation_ru": "Hand (рука) + Tuch (ткань) = Handtuch — полотенце для рук",
    },
    {
        "id": "weinglas_001",
        "compound": "Weinglas",
        "article": "das",
        "meaning_ru": "бокал для вина",
        "difficulty": "A2",
        "category": "food",
        "parts": [{"word": "Wein", "meaning_ru": "вино"}, {"word": "Glas", "meaning_ru": "стакан"}],
        "wrong_options": ["Saftglas", "Weinkaraffe", "Bierglas"],
        "explanation_ru": "Wein (вино) + Glas (стакан) = Weinglas",
    },
    {
        "id": "kaffeetasse_001",
        "compound": "Kaffeetasse",
        "article": "die",
        "meaning_ru": "кофейная чашка",
        "difficulty": "A2",
        "category": "food",
        "parts": [{"word": "Kaffee", "meaning_ru": "кофе"}, {"word": "Tasse", "meaning_ru": "чашка"}],
        "wrong_options": ["Teetasse", "Kaffeebecher", "Suppentasse"],
        "explanation_ru": "Kaffee (кофе) + Tasse (чашка) = Kaffeetasse",
    },
    {
        "id": "brotmesser_001",
        "compound": "Brotmesser",
        "article": "das",
        "meaning_ru": "хлебный нож",
        "difficulty": "A2",
        "category": "food",
        "parts": [{"word": "Brot", "meaning_ru": "хлеб"}, {"word": "Messer", "meaning_ru": "нож"}],
        "wrong_options": ["Buttermesser", "Brotkorb", "Käsemesser"],
        "explanation_ru": "Brot (хлеб) + Messer (нож) = Brotmesser",
    },
    {
        "id": "eiswuerfel_001",
        "compound": "Eiswürfel",
        "article": "der",
        "meaning_ru": "кубик льда",
        "difficulty": "A2",
        "category": "food",
        "parts": [{"word": "Eis", "meaning_ru": "лёд"}, {"word": "Würfel", "meaning_ru": "кубик"}],
        "wrong_options": ["Eisblock", "Zuckerwürfel", "Eisbar"],
        "explanation_ru": "Eis (лёд) + Würfel (кубик) = Eiswürfel — кубик льда",
    },
    {
        "id": "sandkasten_001",
        "compound": "Sandkasten",
        "article": "der",
        "meaning_ru": "песочница",
        "difficulty": "A2",
        "category": "outdoor",
        "parts": [{"word": "Sand", "meaning_ru": "песок"}, {"word": "Kasten", "meaning_ru": "ящик"}],
        "wrong_options": ["Sandburg", "Briefkasten", "Sandstrand"],
        "explanation_ru": "Sand (песок) + Kasten (ящик) = Sandkasten — песочница",
    },
    {
        "id": "kinderwagen_001",
        "compound": "Kinderwagen",
        "article": "der",
        "meaning_ru": "детская коляска",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Kind", "meaning_ru": "ребёнок"}, {"word": "Wagen", "meaning_ru": "повозка"}],
        "wrong_options": ["Krankenwagen", "Kinderbett", "Sportwagen"],
        "explanation_ru": "Kind (ребёнок) + Wagen (повозка) = Kinderwagen — детская коляска",
    },
    {
        "id": "buecherregal_001",
        "compound": "Bücherregal",
        "article": "das",
        "meaning_ru": "книжная полка",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Bücher", "meaning_ru": "книги"}, {"word": "Regal", "meaning_ru": "полка"}],
        "wrong_options": ["Bücherturm", "Schuhregal", "Büchermarkt"],
        "explanation_ru": "Bücher (книги) + Regal (стеллаж) = Bücherregal",
    },
    {
        "id": "tischtuch_001",
        "compound": "Tischtuch",
        "article": "das",
        "meaning_ru": "скатерть",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Tisch", "meaning_ru": "стол"}, {"word": "Tuch", "meaning_ru": "ткань"}],
        "wrong_options": ["Handtuch", "Tischdecke", "Badetuch"],
        "explanation_ru": "Tisch (стол) + Tuch (ткань) = Tischtuch — скатерть",
    },
    {
        "id": "mondlicht_001",
        "compound": "Mondlicht",
        "article": "das",
        "meaning_ru": "лунный свет",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Mond", "meaning_ru": "луна"}, {"word": "Licht", "meaning_ru": "свет"}],
        "wrong_options": ["Mondschein", "Sonnenlicht", "Sternlicht"],
        "explanation_ru": "Mond (луна) + Licht (свет) = Mondlicht — лунный свет",
    },
    {
        "id": "feuerwerk_001",
        "compound": "Feuerwerk",
        "article": "das",
        "meaning_ru": "фейерверк",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Feuer", "meaning_ru": "огонь"}, {"word": "Werk", "meaning_ru": "дело/творение"}],
        "wrong_options": ["Feuerwehr", "Kunstwerk", "Feuerlöscher"],
        "explanation_ru": "Feuer (огонь) + Werk (творение) = Feuerwerk — фейерверк",
    },
    {
        "id": "vogelhaus_001",
        "compound": "Vogelhaus",
        "article": "das",
        "meaning_ru": "скворечник",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Vogel", "meaning_ru": "птица"}, {"word": "Haus", "meaning_ru": "дом"}],
        "wrong_options": ["Hundehaus", "Vogelkäfig", "Baumhaus"],
        "explanation_ru": "Vogel (птица) + Haus (домик) = Vogelhaus — скворечник",
    },
    {
        "id": "schneeball_001",
        "compound": "Schneeball",
        "article": "der",
        "meaning_ru": "снежок",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Schnee", "meaning_ru": "снег"}, {"word": "Ball", "meaning_ru": "мяч"}],
        "wrong_options": ["Schneemann", "Fußball", "Schneeflocke"],
        "explanation_ru": "Schnee (снег) + Ball (мяч) = Schneeball — снежок",
    },
    {
        "id": "nashorn_001",
        "compound": "Nashorn",
        "article": "das",
        "meaning_ru": "носорог",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Nase", "meaning_ru": "нос"}, {"word": "Horn", "meaning_ru": "рог"}],
        "wrong_options": ["Einhorn", "Nasenbär", "Stoßzahn"],
        "explanation_ru": "Nase (нос) + Horn (рог) = Nashorn — носорог, буквально «носорог»",
    },
    {
        "id": "apfelsaft_001",
        "compound": "Apfelsaft",
        "article": "der",
        "meaning_ru": "яблочный сок",
        "difficulty": "A2",
        "category": "food",
        "parts": [{"word": "Apfel", "meaning_ru": "яблоко"}, {"word": "Saft", "meaning_ru": "сок"}],
        "wrong_options": ["Orangensaft", "Apfelkuchen", "Traubensaft"],
        "explanation_ru": "Apfel (яблоко) + Saft (сок) = Apfelsaft",
    },
    {
        "id": "orangensaft_001",
        "compound": "Orangensaft",
        "article": "der",
        "meaning_ru": "апельсиновый сок",
        "difficulty": "A2",
        "category": "food",
        "parts": [{"word": "Orange", "meaning_ru": "апельсин"}, {"word": "Saft", "meaning_ru": "сок"}],
        "wrong_options": ["Apfelsaft", "Orangenhaut", "Zitronensaft"],
        "explanation_ru": "Orange (апельсин) + Saft (сок) = Orangensaft",
    },
    {
        "id": "eisberg_001",
        "compound": "Eisberg",
        "article": "der",
        "meaning_ru": "айсберг",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Eis", "meaning_ru": "лёд"}, {"word": "Berg", "meaning_ru": "гора"}],
        "wrong_options": ["Eisbar", "Steinberg", "Schneeberg"],
        "explanation_ru": "Eis (лёд) + Berg (гора) = Eisberg — айсберг",
    },
    {
        "id": "regenbogen_001",
        "compound": "Regenbogen",
        "article": "der",
        "meaning_ru": "радуга",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Regen", "meaning_ru": "дождь"}, {"word": "Bogen", "meaning_ru": "дуга"}],
        "wrong_options": ["Regenwald", "Pfeilbogen", "Sonnenbogen"],
        "explanation_ru": "Regen (дождь) + Bogen (дуга) = Regenbogen — радуга",
    },
    {
        "id": "schneeflocke_001",
        "compound": "Schneeflocke",
        "article": "die",
        "meaning_ru": "снежинка",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Schnee", "meaning_ru": "снег"}, {"word": "Flocke", "meaning_ru": "хлопья"}],
        "wrong_options": ["Schneemann", "Eiskristall", "Schneesturm"],
        "explanation_ru": "Schnee (снег) + Flocke (хлопья) = Schneeflocke — снежинка",
    },
    {
        "id": "tannenbaum_001",
        "compound": "Tannenbaum",
        "article": "der",
        "meaning_ru": "ёлка",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Tanne", "meaning_ru": "пихта"}, {"word": "Baum", "meaning_ru": "дерево"}],
        "wrong_options": ["Tannenzapfen", "Apfelbaum", "Weihnachtsbaum"],
        "explanation_ru": "Tanne (пихта) + Baum (дерево) = Tannenbaum — ёлка",
    },
    {
        "id": "birnbaum_001",
        "compound": "Birnbaum",
        "article": "der",
        "meaning_ru": "грушевое дерево",
        "difficulty": "A2",
        "category": "nature",
        "parts": [{"word": "Birne", "meaning_ru": "груша"}, {"word": "Baum", "meaning_ru": "дерево"}],
        "wrong_options": ["Apfelbaum", "Birnensaft", "Kirschbaum"],
        "explanation_ru": "Birne (груша) + Baum (дерево) = Birnbaum",
    },
    {
        "id": "segelboot_001",
        "compound": "Segelboot",
        "article": "das",
        "meaning_ru": "парусная лодка",
        "difficulty": "A2",
        "category": "transport",
        "parts": [{"word": "Segel", "meaning_ru": "парус"}, {"word": "Boot", "meaning_ru": "лодка"}],
        "wrong_options": ["Segelschiff", "Motorboot", "Ruderboot"],
        "explanation_ru": "Segel (парус) + Boot (лодка) = Segelboot",
    },
    {
        "id": "kuhstall_001",
        "compound": "Kuhstall",
        "article": "der",
        "meaning_ru": "коровник",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Kuh", "meaning_ru": "корова"}, {"word": "Stall", "meaning_ru": "сарай"}],
        "wrong_options": ["Pferdestall", "Kuhweide", "Hühnerstall"],
        "explanation_ru": "Kuh (корова) + Stall (стойло) = Kuhstall — коровник",
    },
    {
        "id": "schafwolle_001",
        "compound": "Schafwolle",
        "article": "die",
        "meaning_ru": "овечья шерсть",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Schaf", "meaning_ru": "овца"}, {"word": "Wolle", "meaning_ru": "шерсть"}],
        "wrong_options": ["Schafskäse", "Baumwolle", "Ziegenwolle"],
        "explanation_ru": "Schaf (овца) + Wolle (шерсть) = Schafwolle",
    },
    {
        "id": "katzenkorb_001",
        "compound": "Katzenkorb",
        "article": "der",
        "meaning_ru": "переноска для кота",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Katze", "meaning_ru": "кот"}, {"word": "Korb", "meaning_ru": "корзина"}],
        "wrong_options": ["Hundekorb", "Katzenhaus", "Brotkorb"],
        "explanation_ru": "Katze (кот) + Korb (корзина) = Katzenkorb",
    },
    {
        "id": "puppenhaus_001",
        "compound": "Puppenhaus",
        "article": "das",
        "meaning_ru": "кукольный домик",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Puppe", "meaning_ru": "кукла"}, {"word": "Haus", "meaning_ru": "дом"}],
        "wrong_options": ["Baumhaus", "Puppenwagen", "Spielzeughaus"],
        "explanation_ru": "Puppe (кукла) + Haus (домик) = Puppenhaus",
    },
    {
        "id": "goldring_001",
        "compound": "Goldring",
        "article": "der",
        "meaning_ru": "золотое кольцо",
        "difficulty": "A2",
        "category": "clothing",
        "parts": [{"word": "Gold", "meaning_ru": "золото"}, {"word": "Ring", "meaning_ru": "кольцо"}],
        "wrong_options": ["Silberring", "Golduhr", "Ohrring"],
        "explanation_ru": "Gold (золото) + Ring (кольцо) = Goldring",
    },
    {
        "id": "zahnbuerste_001",
        "compound": "Zahnbürste",
        "article": "die",
        "meaning_ru": "зубная щётка",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Zahn", "meaning_ru": "зуб"}, {"word": "Bürste", "meaning_ru": "щётка"}],
        "wrong_options": ["Haarbürste", "Zahnpasta", "Nagelbürste"],
        "explanation_ru": "Zahn (зуб) + Bürste (щётка) = Zahnbürste",
    },
    {
        "id": "zahnpasta_001",
        "compound": "Zahnpasta",
        "article": "die",
        "meaning_ru": "зубная паста",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Zahn", "meaning_ru": "зуб"}, {"word": "Pasta", "meaning_ru": "паста"}],
        "wrong_options": ["Zahnbürste", "Haarpasta", "Zahncreme"],
        "explanation_ru": "Zahn (зуб) + Pasta (паста) = Zahnpasta",
    },
    {
        "id": "haarbuerste_001",
        "compound": "Haarbürste",
        "article": "die",
        "meaning_ru": "расчёска/щётка для волос",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Haar", "meaning_ru": "волосы"}, {"word": "Bürste", "meaning_ru": "щётка"}],
        "wrong_options": ["Zahnbürste", "Haarschmuck", "Nagelbürste"],
        "explanation_ru": "Haar (волосы) + Bürste (щётка) = Haarbürste",
    },
    {
        "id": "tintenfisch_001",
        "compound": "Tintenfisch",
        "article": "der",
        "meaning_ru": "осьминог / кальмар",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Tinte", "meaning_ru": "чернила"}, {"word": "Fisch", "meaning_ru": "рыба"}],
        "wrong_options": ["Schwertfisch", "Tintenstift", "Hammerhai"],
        "explanation_ru": "Tinte (чернила) + Fisch (рыба) = Tintenfisch — осьминог, буквально «чернильная рыба»",
    },
    {
        "id": "schwertfisch_001",
        "compound": "Schwertfisch",
        "article": "der",
        "meaning_ru": "рыба-меч",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Schwert", "meaning_ru": "меч"}, {"word": "Fisch", "meaning_ru": "рыба"}],
        "wrong_options": ["Tintenfisch", "Schwertschlucker", "Hammerhai"],
        "explanation_ru": "Schwert (меч) + Fisch (рыба) = Schwertfisch",
    },
    {
        "id": "strandkorb_001",
        "compound": "Strandkorb",
        "article": "der",
        "meaning_ru": "плетёное пляжное кресло",
        "difficulty": "A2",
        "category": "outdoor",
        "parts": [{"word": "Strand", "meaning_ru": "пляж"}, {"word": "Korb", "meaning_ru": "корзина"}],
        "wrong_options": ["Katzenkorb", "Strandtasche", "Gartenkorb"],
        "explanation_ru": "Strand (пляж) + Korb (корзина) = Strandkorb",
    },
    {
        "id": "windmuehle_001",
        "compound": "Windmühle",
        "article": "die",
        "meaning_ru": "ветряная мельница",
        "difficulty": "A2",
        "category": "outdoor",
        "parts": [{"word": "Wind", "meaning_ru": "ветер"}, {"word": "Mühle", "meaning_ru": "мельница"}],
        "wrong_options": ["Windrad", "Wassermühle", "Windstärke"],
        "explanation_ru": "Wind (ветер) + Mühle (мельница) = Windmühle",
    },
    {
        "id": "bienenstock_001",
        "compound": "Bienenstock",
        "article": "der",
        "meaning_ru": "улей",
        "difficulty": "A2",
        "category": "animals",
        "parts": [{"word": "Biene", "meaning_ru": "пчела"}, {"word": "Stock", "meaning_ru": "палка/улей"}],
        "wrong_options": ["Bienenwabe", "Bienenhaus", "Ameisenstock"],
        "explanation_ru": "Biene (пчела) + Stock (улей) = Bienenstock",
    },
    {
        "id": "spielzeug_001",
        "compound": "Spielzeug",
        "article": "das",
        "meaning_ru": "игрушка",
        "difficulty": "A2",
        "category": "home",
        "parts": [{"word": "Spiel", "meaning_ru": "игра"}, {"word": "Zeug", "meaning_ru": "вещи"}],
        "wrong_options": ["Spielplatz", "Werkzeug", "Spielkarte"],
        "explanation_ru": "Spiel (игра) + Zeug (вещи) = Spielzeug — игрушка",
    },
    {
        "id": "pfeilbogen_001",
        "compound": "Pfeilbogen",
        "article": "der",
        "meaning_ru": "лук и стрела",
        "difficulty": "A2",
        "category": "sport",
        "parts": [{"word": "Pfeil", "meaning_ru": "стрела"}, {"word": "Bogen", "meaning_ru": "лук/дуга"}],
        "wrong_options": ["Regenbogen", "Pfeilspitze", "Armbrustbogen"],
        "explanation_ru": "Pfeil (стрела) + Bogen (лук) = Pfeilbogen — лук со стрелой",
    },
    # ── B1 ──────────────────────────────────────────────────────────────────
    {
        "id": "kuehlschrank_001",
        "compound": "Kühlschrank",
        "article": "der",
        "meaning_ru": "холодильник",
        "difficulty": "B1",
        "category": "home",
        "parts": [{"word": "Eis", "meaning_ru": "лёд/холод"}, {"word": "Schrank", "meaning_ru": "шкаф"}],
        "wrong_options": ["Gefrierschrank", "Kleiderschrank", "Kühlbox"],
        "explanation_ru": "Kühl (холод) + Schrank (шкаф) = Kühlschrank — холодильник",
    },
    {
        "id": "eieruhr_001",
        "compound": "Eieruhr",
        "article": "die",
        "meaning_ru": "кухонный таймер (яйцевидный)",
        "difficulty": "B1",
        "category": "food",
        "parts": [{"word": "Birne", "meaning_ru": "яйцо (форма)"}, {"word": "Uhr", "meaning_ru": "часы"}],
        "wrong_options": ["Küchenuhr", "Eierbecher", "Sanduhr"],
        "explanation_ru": "Ei (яйцо) + Uhr (часы) = Eieruhr — таймер в форме яйца",
    },
    {
        "id": "leuchtturm_001",
        "compound": "Leuchtturm",
        "article": "der",
        "meaning_ru": "маяк",
        "difficulty": "B1",
        "category": "outdoor",
        "parts": [{"word": "Licht", "meaning_ru": "свет"}, {"word": "Turm", "meaning_ru": "башня"}],
        "wrong_options": ["Kirchturm", "Leuchtrakete", "Wasserturm"],
        "explanation_ru": "Leuchten (светить) + Turm (башня) = Leuchtturm — маяк",
    },
    {
        "id": "fallschirm_001",
        "compound": "Fallschirm",
        "article": "der",
        "meaning_ru": "парашют",
        "difficulty": "B1",
        "category": "sport",
        "parts": [{"word": "Fall", "meaning_ru": "падение"}, {"word": "Schirm", "meaning_ru": "зонт/экран"}],
        "wrong_options": ["Regenschirm", "Fallzeit", "Sonnenschirm"],
        "explanation_ru": "Fall (падение) + Schirm (зонт) = Fallschirm — парашют, буквально «зонт для падения»",
    },
    {
        "id": "dampfschiff_001",
        "compound": "Dampfschiff",
        "article": "das",
        "meaning_ru": "пароход",
        "difficulty": "B1",
        "category": "transport",
        "parts": [{"word": "Dampf", "meaning_ru": "пар"}, {"word": "Schiff", "meaning_ru": "корабль"}],
        "wrong_options": ["Segelschiff", "Dampflokomotive", "Kriegsschiff"],
        "explanation_ru": "Dampf (пар) + Schiff (корабль) = Dampfschiff — пароход",
    },
    {
        "id": "bahnhof_001",
        "compound": "Bahnhof",
        "article": "der",
        "meaning_ru": "железнодорожный вокзал",
        "difficulty": "B1",
        "category": "transport",
        "parts": [{"word": "Bahn", "meaning_ru": "поезд/путь"}, {"word": "Hof", "meaning_ru": "двор"}],
        "wrong_options": ["Flughafen", "Bahngleis", "Schlachthof"],
        "explanation_ru": "Bahn (железная дорога) + Hof (двор) = Bahnhof — вокзал",
    },
    {
        "id": "flughafen_001",
        "compound": "Flughafen",
        "article": "der",
        "meaning_ru": "аэропорт",
        "difficulty": "B1",
        "category": "transport",
        "parts": [{"word": "Flug", "meaning_ru": "полёт"}, {"word": "Hafen", "meaning_ru": "гавань"}],
        "wrong_options": ["Bahnhof", "Flugzeug", "Seehafen"],
        "explanation_ru": "Flug (полёт) + Hafen (гавань) = Flughafen — аэропорт",
    },
    {
        "id": "bergmann_001",
        "compound": "Bergmann",
        "article": "der",
        "meaning_ru": "шахтёр / горнорабочий",
        "difficulty": "B1",
        "category": "work",
        "parts": [{"word": "Berg", "meaning_ru": "гора"}, {"word": "Mann", "meaning_ru": "мужчина"}],
        "wrong_options": ["Bergsteiger", "Feuermann", "Bergdorf"],
        "explanation_ru": "Berg (гора) + Mann (человек) = Bergmann — шахтёр",
    },
    {
        "id": "eichhoernchen_001",
        "compound": "Eichhörnchen",
        "article": "das",
        "meaning_ru": "белка",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Eiche", "meaning_ru": "дуб"}, {"word": "Hörnchen", "meaning_ru": "рожок/круассан"}],
        "wrong_options": ["Nashorn", "Einhorn", "Baumhörnchen"],
        "explanation_ru": "Eiche (дуб) + Hörnchen (рожок) = Eichhörnchen — белка живёт на дубах",
    },
    {
        "id": "steinpilz_001",
        "compound": "Steinpilz",
        "article": "der",
        "meaning_ru": "белый гриб",
        "difficulty": "B1",
        "category": "nature",
        "parts": [{"word": "Stein", "meaning_ru": "камень"}, {"word": "Pilz", "meaning_ru": "гриб"}],
        "wrong_options": ["Waldpilz", "Steinobst", "Fliegenpilz"],
        "explanation_ru": "Stein (камень) + Pilz (гриб) = Steinpilz — боровик",
    },
    {
        "id": "meerschweinchen_001",
        "compound": "Meerschweinchen",
        "article": "das",
        "meaning_ru": "морская свинка",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Meer", "meaning_ru": "море"}, {"word": "Schwein", "meaning_ru": "свинья"}],
        "wrong_options": ["Meerestier", "Wildschwein", "Seehund"],
        "explanation_ru": "Meer (море) + Schweinchen (свинка) = Meerschweinchen — морская свинка",
    },
    {
        "id": "spiegelei_001",
        "compound": "Spiegelei",
        "article": "das",
        "meaning_ru": "яичница-глазунья",
        "difficulty": "B1",
        "category": "food",
        "parts": [{"word": "Spiegel", "meaning_ru": "зеркало"}, {"word": "Birne", "meaning_ru": "яйцо"}],
        "wrong_options": ["Rührei", "Spiegelkarpfen", "Omelette"],
        "explanation_ru": "Spiegel (зеркало) + Ei (яйцо) = Spiegelei — яичница-глазунья напоминает зеркало",
    },
    {
        "id": "rollstuhl_001",
        "compound": "Rollstuhl",
        "article": "der",
        "meaning_ru": "инвалидная коляска",
        "difficulty": "B1",
        "category": "home",
        "parts": [{"word": "Rollen", "meaning_ru": "катиться"}, {"word": "Stuhl", "meaning_ru": "стул"}],
        "wrong_options": ["Schaukelstuhl", "Rolltreppe", "Liegestuhl"],
        "explanation_ru": "Rollen (катиться) + Stuhl (стул) = Rollstuhl — кресло на колёсах",
    },
    {
        "id": "schaukelstuhl_001",
        "compound": "Schaukelstuhl",
        "article": "der",
        "meaning_ru": "кресло-качалка",
        "difficulty": "B1",
        "category": "home",
        "parts": [{"word": "Schaukeln", "meaning_ru": "качаться"}, {"word": "Stuhl", "meaning_ru": "стул"}],
        "wrong_options": ["Rollstuhl", "Liegestuhl", "Schaukelboot"],
        "explanation_ru": "Schaukeln (качаться) + Stuhl (стул) = Schaukelstuhl — кресло-качалка",
    },
    {
        "id": "waschmaschine_001",
        "compound": "Waschmaschine",
        "article": "die",
        "meaning_ru": "стиральная машина",
        "difficulty": "B1",
        "category": "home",
        "parts": [{"word": "Waschen", "meaning_ru": "стирать"}, {"word": "Maschine", "meaning_ru": "машина"}],
        "wrong_options": ["Kaffeemaschine", "Waschmittel", "Spülmaschine"],
        "explanation_ru": "Waschen (стирать) + Maschine (машина) = Waschmaschine",
    },
    {
        "id": "kaffeemaschine_001",
        "compound": "Kaffeemaschine",
        "article": "die",
        "meaning_ru": "кофемашина",
        "difficulty": "B1",
        "category": "food",
        "parts": [{"word": "Kaffee", "meaning_ru": "кофе"}, {"word": "Maschine", "meaning_ru": "машина"}],
        "wrong_options": ["Waschmaschine", "Kaffeekanne", "Nähmaschine"],
        "explanation_ru": "Kaffee (кофе) + Maschine (машина) = Kaffeemaschine",
    },
    {
        "id": "naehmaschine_001",
        "compound": "Nähmaschine",
        "article": "die",
        "meaning_ru": "швейная машина",
        "difficulty": "B1",
        "category": "home",
        "parts": [{"word": "Nähen", "meaning_ru": "шить"}, {"word": "Maschine", "meaning_ru": "машина"}],
        "wrong_options": ["Waschmaschine", "Nähnadel", "Kaffeemaschine"],
        "explanation_ru": "Nähen (шить) + Maschine (машина) = Nähmaschine",
    },
    {
        "id": "schreibmaschine_001",
        "compound": "Schreibmaschine",
        "article": "die",
        "meaning_ru": "печатная машинка",
        "difficulty": "B1",
        "category": "work",
        "parts": [{"word": "Schreiben", "meaning_ru": "писать"}, {"word": "Maschine", "meaning_ru": "машина"}],
        "wrong_options": ["Schreibtisch", "Nähmaschine", "Druckmaschine"],
        "explanation_ru": "Schreiben (писать) + Maschine (машина) = Schreibmaschine — печатная машинка",
    },
    {
        "id": "lampenschirm_001",
        "compound": "Lampenschirm",
        "article": "der",
        "meaning_ru": "абажур",
        "difficulty": "B1",
        "category": "home",
        "parts": [{"word": "Lampe", "meaning_ru": "лампа"}, {"word": "Schirm", "meaning_ru": "экран/зонт"}],
        "wrong_options": ["Regenschirm", "Lampenfieber", "Lichtschirm"],
        "explanation_ru": "Lampe (лампа) + Schirm (экран) = Lampenschirm — абажур",
    },
    {
        "id": "fingernagel_001",
        "compound": "Fingernagel",
        "article": "der",
        "meaning_ru": "ноготь",
        "difficulty": "B1",
        "category": "body",
        "parts": [{"word": "Finger", "meaning_ru": "палец"}, {"word": "Nagel", "meaning_ru": "гвоздь"}],
        "wrong_options": ["Zehennagel", "Fingerkuppe", "Nagelschere"],
        "explanation_ru": "Finger (палец) + Nagel (гвоздь/ноготь) = Fingernagel",
    },
    {
        "id": "hahnenkamm_001",
        "compound": "Hahnenkamm",
        "article": "der",
        "meaning_ru": "петушиный гребень",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Hahn", "meaning_ru": "петух"}, {"word": "Kamm", "meaning_ru": "гребень/расчёска"}],
        "wrong_options": ["Hahnenschrei", "Haarkamm", "Hühnerkamm"],
        "explanation_ru": "Hahn (петух) + Kamm (гребень) = Hahnenkamm",
    },
    {
        "id": "pferdeschwanz_001",
        "compound": "Pferdeschwanz",
        "article": "der",
        "meaning_ru": "конский хвост / хвостик (причёска)",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Pferd", "meaning_ru": "лошадь"}, {"word": "Schwanz", "meaning_ru": "хвост"}],
        "wrong_options": ["Pferdemähne", "Katzenschwanz", "Fuchsschwanz"],
        "explanation_ru": "Pferd (лошадь) + Schwanz (хвост) = Pferdeschwanz — хвостик как причёска",
    },
    {
        "id": "elefantenruessel_001",
        "compound": "Elefantenrüssel",
        "article": "der",
        "meaning_ru": "хобот слона",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Elefant", "meaning_ru": "слон"}, {"word": "Rüssel", "meaning_ru": "хобот"}],
        "wrong_options": ["Elefantenzahn", "Nashorn", "Walrüssel"],
        "explanation_ru": "Elefant (слон) + Rüssel (хобот) = Elefantenrüssel",
    },
    {
        "id": "loewenmaehne_001",
        "compound": "Löwenmähne",
        "article": "die",
        "meaning_ru": "грива льва",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Löwe", "meaning_ru": "лев"}, {"word": "Mähne", "meaning_ru": "грива"}],
        "wrong_options": ["Löwenzahn", "Pferdemähne", "Tigerfell"],
        "explanation_ru": "Löwe (лев) + Mähne (грива) = Löwenmähne",
    },
    {
        "id": "hammerhai_001",
        "compound": "Hammerhai",
        "article": "der",
        "meaning_ru": "рыба-молот",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Hammer", "meaning_ru": "молоток"}, {"word": "Hai", "meaning_ru": "акула"}],
        "wrong_options": ["Schwertfisch", "Hammerkopf", "Weißer Hai"],
        "explanation_ru": "Hammer (молоток) + Hai (акула) = Hammerhai — рыба-молот",
    },
    {
        "id": "mondsichel_001",
        "compound": "Mondsichel",
        "article": "die",
        "meaning_ru": "серп луны",
        "difficulty": "B1",
        "category": "nature",
        "parts": [{"word": "Mond", "meaning_ru": "луна"}, {"word": "Sichel", "meaning_ru": "серп"}],
        "wrong_options": ["Mondschein", "Erntesichel", "Halbmond"],
        "explanation_ru": "Mond (луна) + Sichel (серп) = Mondsichel — серп луны",
    },
    {
        "id": "regenwald_001",
        "compound": "Regenwald",
        "article": "der",
        "meaning_ru": "тропический лес",
        "difficulty": "B1",
        "category": "nature",
        "parts": [{"word": "Regen", "meaning_ru": "дождь"}, {"word": "Wald", "meaning_ru": "лес"}],
        "wrong_options": ["Regenmantel", "Nadelwald", "Regenbogen"],
        "explanation_ru": "Regen (дождь) + Wald (лес) = Regenwald — влажный тропический лес",
    },
    {
        "id": "waldbrand_001",
        "compound": "Waldbrand",
        "article": "der",
        "meaning_ru": "лесной пожар",
        "difficulty": "B1",
        "category": "nature",
        "parts": [{"word": "Wald", "meaning_ru": "лес"}, {"word": "Brand", "meaning_ru": "пожар"}],
        "wrong_options": ["Waldboden", "Großbrand", "Stadtbrand"],
        "explanation_ru": "Wald (лес) + Brand (пожар) = Waldbrand",
    },
    {
        "id": "pferdestall_001",
        "compound": "Pferdestall",
        "article": "der",
        "meaning_ru": "конюшня",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Pferd", "meaning_ru": "лошадь"}, {"word": "Stall", "meaning_ru": "стойло"}],
        "wrong_options": ["Kuhstall", "Pferdeweide", "Hühnerstall"],
        "explanation_ru": "Pferd (лошадь) + Stall (стойло) = Pferdestall — конюшня",
    },
    {
        "id": "huehner_stall_001",
        "compound": "Hühnerstall",
        "article": "der",
        "meaning_ru": "курятник",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Huhn", "meaning_ru": "курица"}, {"word": "Stall", "meaning_ru": "сарай"}],
        "wrong_options": ["Kuhstall", "Hühnerei", "Pferdestall"],
        "explanation_ru": "Huhn (курица) + Stall (сарай) = Hühnerstall — курятник",
    },
    {
        "id": "angelrute_001",
        "compound": "Angelrute",
        "article": "die",
        "meaning_ru": "удочка",
        "difficulty": "B1",
        "category": "sport",
        "parts": [{"word": "Angel", "meaning_ru": "крючок/удочка"}, {"word": "Rute", "meaning_ru": "прут/удилище"}],
        "wrong_options": ["Angelschnur", "Wanderrute", "Fischnetz"],
        "explanation_ru": "Angel (крючок/снасть) + Rute (прут) = Angelrute",
    },
    {
        "id": "krankenwagen_001",
        "compound": "Krankenwagen",
        "article": "der",
        "meaning_ru": "машина скорой помощи",
        "difficulty": "B1",
        "category": "work",
        "parts": [{"word": "Kranke", "meaning_ru": "больной человек"}, {"word": "Wagen", "meaning_ru": "машина"}],
        "wrong_options": ["Kinderwagen", "Krankenbett", "Feuerwehrauto"],
        "explanation_ru": "Kranke (больной) + Wagen (машина) = Krankenwagen — скорая помощь",
    },
    {
        "id": "zuckerhut_001",
        "compound": "Zuckerhut",
        "article": "der",
        "meaning_ru": "сахарная голова (сахарная конусная форма)",
        "difficulty": "B1",
        "category": "food",
        "parts": [{"word": "Zucker", "meaning_ru": "сахар"}, {"word": "Hut", "meaning_ru": "шляпа"}],
        "wrong_options": ["Zuckerstange", "Strohhut", "Zuckerbrot"],
        "explanation_ru": "Zucker (сахар) + Hut (шляпа) = Zuckerhut — сахарная голова в форме конуса",
    },
    {
        "id": "honigwabe_001",
        "compound": "Honigwabe",
        "article": "die",
        "meaning_ru": "медовая соты",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Honig", "meaning_ru": "мёд"}, {"word": "Wabe", "meaning_ru": "соты"}],
        "wrong_options": ["Bienenwabe", "Honigbiene", "Wachswabe"],
        "explanation_ru": "Honig (мёд) + Wabe (соты) = Honigwabe",
    },
    {
        "id": "meeresfrüchte_001",
        "compound": "Meeresfrüchte",
        "article": "die",
        "meaning_ru": "морепродукты",
        "difficulty": "B1",
        "category": "food",
        "parts": [{"word": "Meer", "meaning_ru": "море"}, {"word": "Früchte", "meaning_ru": "плоды/фрукты"}],
        "wrong_options": ["Meerestier", "Waldfrüchte", "Gartenfrüchte"],
        "explanation_ru": "Meer (море) + Früchte (плоды) = Meeresfrüchte — морепродукты",
    },
    {
        "id": "kuckucksuhr_001",
        "compound": "Kuckucksuhr",
        "article": "die",
        "meaning_ru": "часы с кукушкой",
        "difficulty": "B1",
        "category": "home",
        "parts": [{"word": "Kuckuck", "meaning_ru": "кукушка"}, {"word": "Uhr", "meaning_ru": "часы"}],
        "wrong_options": ["Wanduhr", "Kuckucksruf", "Sanduhr"],
        "explanation_ru": "Kuckuck (кукушка) + Uhr (часы) = Kuckucksuhr",
    },
    {
        "id": "mondrakete_001",
        "compound": "Mondrakete",
        "article": "die",
        "meaning_ru": "лунная ракета",
        "difficulty": "B1",
        "category": "science",
        "parts": [{"word": "Mond", "meaning_ru": "луна"}, {"word": "Rakete", "meaning_ru": "ракета"}],
        "wrong_options": ["Mondlandung", "Raumrakete", "Mondschein"],
        "explanation_ru": "Mond (луна) + Rakete (ракета) = Mondrakete",
    },
    {
        "id": "sternenhimmel_001",
        "compound": "Sternenhimmel",
        "article": "der",
        "meaning_ru": "звёздное небо",
        "difficulty": "B1",
        "category": "nature",
        "parts": [{"word": "Stern", "meaning_ru": "звезда"}, {"word": "Himmel", "meaning_ru": "небо"}],
        "wrong_options": ["Sternschnuppe", "Blauhimmel", "Mondschein"],
        "explanation_ru": "Stern (звезда) + Himmel (небо) = Sternenhimmel",
    },
    {
        "id": "blumenkohl_001",
        "compound": "Blumenkohl",
        "article": "der",
        "meaning_ru": "цветная капуста",
        "difficulty": "B1",
        "category": "food",
        "parts": [{"word": "Blume", "meaning_ru": "цветок"}, {"word": "Kohl", "meaning_ru": "капуста"}],
        "wrong_options": ["Rotkohl", "Blumenstrauß", "Brokkoli"],
        "explanation_ru": "Blume (цветок) + Kohl (капуста) = Blumenkohl — цветная капуста",
    },
    {
        "id": "kopfschmerzen_001",
        "compound": "Kopfschmerzen",
        "article": "die",
        "meaning_ru": "головная боль",
        "difficulty": "B1",
        "category": "health",
        "parts": [{"word": "Kopf", "meaning_ru": "голова"}, {"word": "Schmerzen", "meaning_ru": "боль"}],
        "wrong_options": ["Bauchschmerzen", "Kopfkissen", "Rückenschmerzen"],
        "explanation_ru": "Kopf (голова) + Schmerzen (боль) = Kopfschmerzen — головная боль",
    },
    {
        "id": "bauchschmerzen_001",
        "compound": "Bauchschmerzen",
        "article": "die",
        "meaning_ru": "боль в животе",
        "difficulty": "B1",
        "category": "health",
        "parts": [{"word": "Bauch", "meaning_ru": "живот"}, {"word": "Schmerzen", "meaning_ru": "боль"}],
        "wrong_options": ["Kopfschmerzen", "Bauchmuskel", "Zahnschmerzen"],
        "explanation_ru": "Bauch (живот) + Schmerzen (боль) = Bauchschmerzen",
    },
    {
        "id": "schreibtisch_001",
        "compound": "Schreibtisch",
        "article": "der",
        "meaning_ru": "письменный стол",
        "difficulty": "B1",
        "category": "home",
        "parts": [{"word": "Schreiben", "meaning_ru": "писать"}, {"word": "Tisch", "meaning_ru": "стол"}],
        "wrong_options": ["Esstisch", "Schreibheft", "Couchtisch"],
        "explanation_ru": "Schreiben (писать) + Tisch (стол) = Schreibtisch",
    },
    {
        "id": "bratpfanne_001",
        "compound": "Bratpfanne",
        "article": "die",
        "meaning_ru": "сковорода",
        "difficulty": "B1",
        "category": "food",
        "parts": [{"word": "Braten", "meaning_ru": "жарить"}, {"word": "Pfanne", "meaning_ru": "сковорода"}],
        "wrong_options": ["Kochtopf", "Backblech", "Grillpfanne"],
        "explanation_ru": "Braten (жарить) + Pfanne (сковорода) = Bratpfanne",
    },
    {
        "id": "suppenkelle_001",
        "compound": "Suppenkelle",
        "article": "die",
        "meaning_ru": "половник для супа",
        "difficulty": "B1",
        "category": "food",
        "parts": [{"word": "Suppe", "meaning_ru": "суп"}, {"word": "Kelle", "meaning_ru": "ковш"}],
        "wrong_options": ["Suppenteller", "Schöpfkelle", "Rührkelle"],
        "explanation_ru": "Suppe (суп) + Kelle (ковш) = Suppenkelle",
    },
    {
        "id": "salatschuessel_001",
        "compound": "Salatschüssel",
        "article": "die",
        "meaning_ru": "салатница",
        "difficulty": "B1",
        "category": "food",
        "parts": [{"word": "Salat", "meaning_ru": "салат"}, {"word": "Schüssel", "meaning_ru": "миска"}],
        "wrong_options": ["Suppenschüssel", "Salatgabel", "Obstschale"],
        "explanation_ru": "Salat (салат) + Schüssel (миска) = Salatschüssel",
    },
    {
        "id": "nussbaum_001",
        "compound": "Nussbaum",
        "article": "der",
        "meaning_ru": "ореховое дерево",
        "difficulty": "B1",
        "category": "nature",
        "parts": [{"word": "Nuss", "meaning_ru": "орех"}, {"word": "Baum", "meaning_ru": "дерево"}],
        "wrong_options": ["Apfelbaum", "Nussschale", "Eichenbaum"],
        "explanation_ru": "Nuss (орех) + Baum (дерево) = Nussbaum",
    },
    {
        "id": "tannenzapfen_001",
        "compound": "Tannenzapfen",
        "article": "der",
        "meaning_ru": "еловая/сосновая шишка",
        "difficulty": "B1",
        "category": "nature",
        "parts": [{"word": "Tanne", "meaning_ru": "ель/пихта"}, {"word": "Zapfen", "meaning_ru": "конус"}],
        "wrong_options": ["Tannenzweig", "Kiefernzapfen", "Zapfhahn"],
        "explanation_ru": "Tanne (ель) + Zapfen (конус) = Tannenzapfen — шишка",
    },
    {
        "id": "fingerhut_001",
        "compound": "Fingerhut",
        "article": "der",
        "meaning_ru": "напёрсток (и: наперстянка — цветок)",
        "difficulty": "B1",
        "category": "home",
        "parts": [{"word": "Finger", "meaning_ru": "палец"}, {"word": "Hut", "meaning_ru": "шляпа"}],
        "wrong_options": ["Fingernagel", "Strohhut", "Fingerspitze"],
        "explanation_ru": "Finger (палец) + Hut (шляпа) = Fingerhut — напёрсток «шляпа на палец»",
    },
    {
        "id": "adlerfluegel_001",
        "compound": "Adlerflügel",
        "article": "der",
        "meaning_ru": "крыло орла",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Adler", "meaning_ru": "орёл"}, {"word": "Flügel", "meaning_ru": "крыло"}],
        "wrong_options": ["Adlernest", "Schmetterlingflügel", "Taubenflügel"],
        "explanation_ru": "Adler (орёл) + Flügel (крыло) = Adlerflügel",
    },
    {
        "id": "tigerfell_001",
        "compound": "Tigerfell",
        "article": "das",
        "meaning_ru": "шкура тигра",
        "difficulty": "B1",
        "category": "animals",
        "parts": [{"word": "Tiger", "meaning_ru": "тигр"}, {"word": "Fell", "meaning_ru": "шкура"}],
        "wrong_options": ["Löwenfell", "Tigerzahn", "Schafsfell"],
        "explanation_ru": "Tiger (тигр) + Fell (шкура) = Tigerfell",
    },
    {
        "id": "gansehaut_001",
        "compound": "Gänsehaut",
        "article": "die",
        "meaning_ru": "мурашки по коже",
        "difficulty": "B1",
        "category": "body",
        "parts": [{"word": "Gans", "meaning_ru": "гусь"}, {"word": "Haut", "meaning_ru": "кожа"}],
        "wrong_options": ["Gänsefleisch", "Hühnerbrühe", "Ziegenhaut"],
        "explanation_ru": "Gans (гусь) + Haut (кожа) = Gänsehaut — мурашки как пупырышки кожи гуся",
    },
    {
        "id": "huepfburg_001",
        "compound": "Hüpfburg",
        "article": "die",
        "meaning_ru": "батут-замок",
        "difficulty": "B1",
        "category": "sport",
        "parts": [{"word": "Hüpfen", "meaning_ru": "прыгать"}, {"word": "Burg", "meaning_ru": "замок"}],
        "wrong_options": ["Sandburg", "Trampolin", "Spielplatz"],
        "explanation_ru": "Hüpfen (прыгать) + Burg (замок) = Hüpfburg — надувной замок-батут",
    },
    # ── B2 ──────────────────────────────────────────────────────────────────
    {
        "id": "gluehbirne_001",
        "compound": "Glühbirne",
        "article": "die",
        "meaning_ru": "лампочка",
        "difficulty": "B2",
        "category": "home",
        "parts": [{"word": "Glühen", "meaning_ru": "накаляться/светиться"}, {"word": "Birne", "meaning_ru": "груша"}],
        "wrong_options": ["Neonlampe", "Birnbaum", "Kerze"],
        "explanation_ru": "Glühen (светиться) + Birne (груша) = Glühbirne — лампочка похожа на грушу",
    },
    {
        "id": "katzenjammer_001",
        "compound": "Katzenjammer",
        "article": "der",
        "meaning_ru": "похмелье / жалобный вой",
        "difficulty": "B2",
        "category": "daily",
        "parts": [{"word": "Katze", "meaning_ru": "кот"}, {"word": "Jammer", "meaning_ru": "скорбный вой"}],
        "wrong_options": ["Katzenmusik", "Hundegebell", "Katzenfutter"],
        "explanation_ru": "Katze (кот) + Jammer (вой) = Katzenjammer — похмелье или нытьё",
    },
    {
        "id": "weltreise_001",
        "compound": "Weltreise",
        "article": "die",
        "meaning_ru": "кругосветное путешествие",
        "difficulty": "B2",
        "category": "travel",
        "parts": [{"word": "Welt", "meaning_ru": "мир"}, {"word": "Reise", "meaning_ru": "путешествие"}],
        "wrong_options": ["Weltall", "Fernreise", "Weltrekord"],
        "explanation_ru": "Welt (мир) + Reise (путешествие) = Weltreise",
    },
    {
        "id": "loewenzahn_001",
        "compound": "Löwenzahn",
        "article": "der",
        "meaning_ru": "одуванчик",
        "difficulty": "B2",
        "category": "nature",
        "parts": [{"word": "Löwe", "meaning_ru": "лев"}, {"word": "Zahn", "meaning_ru": "зуб"}],
        "wrong_options": ["Löwenmähne", "Zahnschmerzen", "Gänsblümchen"],
        "explanation_ru": "Löwe (лев) + Zahn (зуб) = Löwenzahn — одуванчик, листья похожи на львиные зубы",
    },
]


def get_rebus_bank_stats() -> dict:
    """Returns counts by difficulty."""
    from collections import Counter
    c = Counter(e["difficulty"] for e in REBUS_COMPOUND_BANK)
    return {"total": len(REBUS_COMPOUND_BANK), "A2": c["A2"], "B1": c["B1"], "B2": c["B2"]}
