"""Русский перевод КАЖДОГО вопроса Wo-Frage — руками, по одному на фразу.

Зачем отдельный файл: в разборе человек видит верную форму («Wovor») и правило
(«о вещи → Wovor, о человеке было бы Vor wem»), но НЕ видит, что фраза вообще
значит. «Wovor ekelt ihr euch?» без перевода — ребус: правило запомнить нельзя,
если непонятно, о чём вопрос.

Перевод нельзя собрать из кусков автоматически: русское управление у каждого
глагола своё («ждать ЧЕГО», «злиться ИЗ-ЗА чего», «пахнуть ЧЕМ»), а у половины
глаголов подлежащее в русском вообще в дательном («тебе противно»). Поэтому
каждая пара (управление, фраза) переведена руками, отдельно для вопроса О ВЕЩИ
и О ЧЕЛОВЕКЕ — они звучат по-разному («Чего ты ждёшь?» / «Кого ты ждёшь?»).

Ключ — (lemma, фраза-вопрос) ровно как в банке `wofrage_generator._BANK`:
опечатка в ключе не «съедет» на соседнюю строку, а честно даст промах, и его
поймает `missing_translations()` (гоняется в тестах).

Значение — (о вещи, о человеке). Пустая строка = такого вопроса этот глагол
не порождает (например, «sprechen mit» спрашивает только о людях).
"""
from __future__ import annotations

# (lemma, фраза) → (перевод вопроса о ВЕЩИ, перевод вопроса о ЧЕЛОВЕКЕ)
QUESTION_RU: dict[tuple[str, str], tuple[str, str]] = {
    # ── über / auf / mit — пополнение банка ──
    ("nachdenken über", "denkst du nach?"): ("О чём ты размышляешь?", ""),
    ("nachdenken über", "denkt ihr nach?"): ("О чём вы размышляете?", ""),
    ("reagieren auf", "reagierst du?"): ("На что ты реагируешь?", "На кого ты реагируешь?"),
    ("reagieren auf", "reagiert ihr?"): ("На что вы реагируете?", "На кого вы реагируете?"),
    ("antworten auf", "antwortest du?"): ("На что ты отвечаешь?", ""),
    ("antworten auf", "antwortet ihr?"): ("На что вы отвечаете?", ""),
    ("sich beschweren über", "beschwerst du dich?"): ("На что ты жалуешься?", "На кого ты жалуешься?"),
    ("sich beschweren über", "beschwert ihr euch?"): ("На что вы жалуетесь?", "На кого вы жалуетесь?"),
    ("sich beschäftigen mit", "beschäftigst du dich?"): ("Чем ты занимаешься?", "Кем ты занимаешься?"),
    ("sich beschäftigen mit", "beschäftigt ihr euch?"): ("Чем вы занимаетесь?", "Кем вы занимаетесь?"),
    ("sich bewerben um", "bewirbst du dich?"): ("На что ты претендуешь?", ""),
    ("sich bewerben um", "bewerbt ihr euch?"): ("На что вы претендуете?", ""),
    ("sich beziehen auf", "beziehst du dich?"): ("На что ты ссылаешься?", "На кого ты ссылаешься?"),
    ("sich beziehen auf", "bezieht ihr euch?"): ("На что вы ссылаетесь?", "На кого вы ссылаетесь?"),
    ("rechnen mit", "rechnest du?"): ("На что ты рассчитываешь?", "На кого ты рассчитываешь?"),
    ("rechnen mit", "rechnet ihr?"): ("На что вы рассчитываете?", "На кого вы рассчитываете?"),
    ("sich einigen auf", "einigt ihr euch?"): ("О чём вы договариваетесь?", ""),
    ("sich einigen auf", "einigen Sie sich?"): ("О чём вы договариваетесь?", ""),
    ("sich einsetzen für", "setzt du dich ein?"): ("За что ты заступаешься?", "За кого ты заступаешься?"),
    ("sich einsetzen für", "setzt ihr euch ein?"): ("За что вы заступаетесь?", "За кого вы заступаетесь?"),
    ("sich beteiligen an", "beteiligst du dich?"): ("В чём ты участвуешь?", ""),
    ("sich beteiligen an", "beteiligt ihr euch?"): ("В чём вы участвуете?", ""),
    ("sich orientieren an", "orientierst du dich?"): ("На что ты ориентируешься?", "На кого ты ориентируешься?"),
    ("sich orientieren an", "orientiert ihr euch?"): ("На что вы ориентируетесь?", "На кого вы ориентируетесь?"),
    ("leiden unter", "leidest du?"): ("От чего ты страдаешь?", "От кого ты страдаешь?"),
    ("leiden unter", "leidet ihr?"): ("От чего вы страдаете?", "От кого вы страдаете?"),
    ("sich richten nach", "richtest du dich?"): ("Чем ты руководствуешься?", "На кого ты ориентируешься?"),
    ("sich richten nach", "richtet ihr euch?"): ("Чем вы руководствуетесь?", "На кого вы ориентируетесь?"),
    ("riechen nach", "riecht es?"): ("Чем пахнет?", ""),
    ("riechen nach", "riecht das?"): ("Чем это пахнет?", ""),
    ("schmecken nach", "schmeckt es?"): ("На что это похоже по вкусу?", ""),
    ("schmecken nach", "schmeckt das?"): ("На что это похоже по вкусу?", ""),
    ("protestieren gegen", "protestierst du?"): ("Против чего ты протестуешь?", "Против кого ты протестуешь?"),
    ("protestieren gegen", "protestiert ihr?"): ("Против чего вы протестуете?", "Против кого вы протестуете?"),
    ("kandidieren für", "kandidierst du?"): ("На что ты баллотируешься?", ""),
    ("kandidieren für", "kandidiert ihr?"): ("На что вы баллотируетесь?", ""),
    ("zählen auf", "zählst du?"): ("На что ты рассчитываешь?", "На кого ты рассчитываешь?"),
    ("zählen auf", "zählt ihr?"): ("На что вы рассчитываете?", "На кого вы рассчитываете?"),
    ("schwärmen von", "schwärmst du?"): ("От чего ты в восторге?", "От кого ты в восторге?"),
    ("schwärmen von", "schwärmt ihr?"): ("От чего вы в восторге?", "От кого вы в восторге?"),
    ("berichten über", "berichtest du?"): ("О чём ты сообщаешь?", "О ком ты сообщаешь?"),
    ("berichten über", "berichtet ihr?"): ("О чём вы сообщаете?", "О ком вы сообщаете?"),
    ("profitieren von", "profitierst du?"): ("От чего ты выигрываешь?", "От кого ты выигрываешь?"),
    ("profitieren von", "profitiert ihr?"): ("От чего вы выигрываете?", "От кого вы выигрываете?"),
    ("sich distanzieren von", "distanzierst du dich?"): ("От чего ты дистанцируешься?", "От кого ты дистанцируешься?"),
    ("sich distanzieren von", "distanziert ihr euch?"): ("От чего вы дистанцируетесь?", "От кого вы дистанцируетесь?"),
    ("abraten von", "rätst du ab?"): ("От чего ты отговариваешь?", ""),
    ("abraten von", "ratet ihr ab?"): ("От чего вы отговариваете?", ""),
    ("sich entwickeln zu", "entwickelt sich das?"): ("Во что это превращается?", ""),
    ("sich entwickeln zu", "entwickelt sich die Lage?"): ("Во что превращается ситуация?", ""),
    ("neigen zu", "neigst du?"): ("К чему ты склонен?", ""),
    ("neigen zu", "neigt ihr?"): ("К чему вы склонны?", ""),
    ("passen zu", "passt das?"): ("К чему это подходит?", "Кому это подходит?"),
    ("passen zu", "passt es gut?"): ("К чему это хорошо подходит?", "Кому это хорошо подходит?"),
    ("vergleichen mit", "vergleichst du das?"): ("С чем ты это сравниваешь?", ""),
    ("vergleichen mit", "vergleicht ihr das?"): ("С чем вы это сравниваете?", ""),
    ("verwechseln mit", "verwechselst du das?"): ("С чем ты это путаешь?", ""),
    ("verwechseln mit", "verwechselt ihr das?"): ("С чем вы это путаете?", ""),
    ("sich anpassen an", "passt du dich an?"): ("К чему ты приспосабливаешься?", ""),
    ("sich anpassen an", "passt ihr euch an?"): ("К чему вы приспосабливаетесь?", ""),
    ("sich bemühen um", "bemühst du dich?"): ("Чего ты добиваешься?", "О ком ты хлопочешь?"),
    ("sich bemühen um", "bemüht ihr euch?"): ("Чего вы добиваетесь?", "О ком вы хлопочете?"),
    ("sich melden bei", "meldest du dich?"): ("", "К кому ты обращаешься?"),
    ("sich melden bei", "meldet ihr euch?"): ("", "К кому вы обращаетесь?"),
    ("sich austauschen über", "tauscht ihr euch aus?"): ("О чём вы обмениваетесь мнениями?", ""),
    ("sich austauschen über", "tauschen Sie sich aus?"): ("О чём вы обмениваетесь мнениями?", ""),
    ("sich eignen für", "eignest du dich?"): ("Для чего ты подходишь?", ""),
    ("sich eignen für", "eignet ihr euch?"): ("Для чего вы подходите?", ""),
    ("dienen zu", "dient das Gerät?"): ("Для чего нужен этот прибор?", ""),
    ("dienen zu", "dient die Regel?"): ("Для чего нужно это правило?", ""),
    ("sich beklagen über", "beklagst du dich?"): ("На что ты сетуешь?", "На кого ты сетуешь?"),
    ("sich beklagen über", "beklagt ihr euch?"): ("На что вы сетуете?", "На кого вы сетуете?"),
    ("sich verabreden mit", "verabredest du dich?"): ("", "С кем ты договариваешься о встрече?"),
    ("sich verabreden mit", "verabredet ihr euch?"): ("", "С кем вы договариваетесь о встрече?"),
    ("sich erholen von", "erholst du dich?"): ("От чего ты приходишь в себя?", ""),
    ("sich erholen von", "erholt ihr euch?"): ("От чего вы приходите в себя?", ""),
    # ── AN + Akkusativ ──
    ("denken an", "denkst du gerade?"): ("О чём ты сейчас думаешь?", "О ком ты сейчас думаешь?"),
    ("denken an", "denkt ihr oft?"): ("О чём вы часто думаете?", "О ком вы часто думаете?"),
    ("sich erinnern an", "erinnerst du dich gern?"): ("О чём ты вспоминаешь с удовольствием?", "О ком ты вспоминаешь с удовольствием?"),
    ("sich erinnern an", "erinnert ihr euch?"): ("О чём вы вспоминаете?", "О ком вы вспоминаете?"),
    ("glauben an", "glaubst du?"): ("Во что ты веришь?", "В кого ты веришь?"),
    ("glauben an", "glaubt ihr wirklich?"): ("Во что вы правда верите?", "В кого вы правда верите?"),
    ("sich gewöhnen an", "gewöhnst du dich?"): ("К чему ты привыкаешь?", "К кому ты привыкаешь?"),
    ("sich gewöhnen an", "gewöhnt ihr euch?"): ("К чему вы привыкаете?", "К кому вы привыкаете?"),
    ("sich wenden an", "wendest du dich?"): ("", "К кому ты обращаешься?"),
    ("sich wenden an", "wendet ihr euch?"): ("", "К кому вы обращаетесь?"),
    ("appellieren an", "appellierst du?"): ("К чему ты апеллируешь?", ""),
    ("appellieren an", "appelliert ihr?"): ("К чему вы апеллируете?", ""),
    # ── AN + Dativ ──
    ("teilnehmen an", "nimmst du teil?"): ("В чём ты участвуешь?", ""),
    ("teilnehmen an", "nehmt ihr teil?"): ("В чём вы участвуете?", ""),
    ("arbeiten an", "arbeitest du?"): ("Над чем ты работаешь?", ""),
    ("arbeiten an", "arbeitet ihr?"): ("Над чем вы работаете?", ""),
    ("zweifeln an", "zweifelst du?"): ("В чём ты сомневаешься?", "В ком ты сомневаешься?"),
    ("zweifeln an", "zweifelt ihr?"): ("В чём вы сомневаетесь?", "В ком вы сомневаетесь?"),
    ("leiden an", "leidest du?"): ("Чем ты болеешь?", ""),
    ("leiden an", "leidet ihr?"): ("Чем вы болеете?", ""),
    # ── AUF + Akkusativ ──
    ("warten auf", "wartest du schon so lange?"): ("Чего ты так долго ждёшь?", "Кого ты так долго ждёшь?"),
    ("warten auf", "wartet ihr gerade?"): ("Чего вы сейчас ждёте?", "Кого вы сейчас ждёте?"),
    ("hoffen auf", "hoffst du?"): ("На что ты надеешься?", ""),
    ("hoffen auf", "hofft ihr insgeheim?"): ("На что вы втайне надеетесь?", ""),
    ("sich freuen auf", "freust du dich am meisten?"): ("Чего ты больше всего ждёшь с нетерпением?", ""),
    ("sich freuen auf", "freut ihr euch so?"): ("Чего вы так ждёте с нетерпением?", ""),
    ("achten auf", "achtest du besonders?"): ("На что ты особенно обращаешь внимание?", "На кого ты особенно обращаешь внимание?"),
    ("achten auf", "achtet ihr?"): ("На что вы обращаете внимание?", "На кого вы обращаете внимание?"),
    ("aufpassen auf", "passt du auf?"): ("За чем ты присматриваешь?", "За кем ты присматриваешь?"),
    ("aufpassen auf", "passt ihr auf?"): ("За чем вы присматриваете?", "За кем вы присматриваете?"),
    ("sich verlassen auf", "verlässt du dich?"): ("На что ты полагаешься?", "На кого ты полагаешься?"),
    ("sich verlassen auf", "verlasst ihr euch?"): ("На что вы полагаетесь?", "На кого вы полагаетесь?"),
    ("sich vorbereiten auf", "bereitest du dich vor?"): ("К чему ты готовишься?", ""),
    ("sich vorbereiten auf", "bereitet ihr euch vor?"): ("К чему вы готовитесь?", ""),
    ("verzichten auf", "verzichtest du?"): ("От чего ты отказываешься?", ""),
    ("verzichten auf", "verzichtet ihr?"): ("От чего вы отказываетесь?", ""),
    ("sich konzentrieren auf", "konzentrierst du dich?"): ("На чём ты сосредотачиваешься?", ""),
    ("sich konzentrieren auf", "konzentriert ihr euch?"): ("На чём вы сосредотачиваетесь?", ""),
    ("bestehen auf", "bestehst du?"): ("На чём ты настаиваешь?", ""),
    ("bestehen auf", "besteht ihr?"): ("На чём вы настаиваете?", ""),
    ("hinweisen auf", "weist du hin?"): ("На что ты указываешь?", ""),
    ("hinweisen auf", "weist ihr hin?"): ("На что вы указываете?", ""),
    ("stolz sein auf", "bist du stolz?"): ("Чем ты гордишься?", "Кем ты гордишься?"),
    ("stolz sein auf", "seid ihr stolz?"): ("Чем вы гордитесь?", "Кем вы гордитесь?"),
    ("neugierig sein auf", "bist du neugierig?"): ("Что тебе любопытно?", "Кто тебе интересен?"),
    ("neugierig sein auf", "seid ihr neugierig?"): ("Что вам любопытно?", "Кто вам интересен?"),
    ("angewiesen sein auf", "bist du angewiesen?"): ("В чём ты нуждаешься?", "От кого ты зависишь?"),
    ("angewiesen sein auf", "seid ihr angewiesen?"): ("В чём вы нуждаетесь?", "От кого вы зависите?"),
    ("Wert legen auf", "legst du Wert?"): ("Чему ты придаёшь значение?", ""),
    ("Wert legen auf", "legt ihr Wert?"): ("Чему вы придаёте значение?", ""),
    ("Lust haben auf", "hast du Lust?"): ("Чего тебе хочется?", ""),
    ("Lust haben auf", "habt ihr Lust?"): ("Чего вам хочется?", ""),
    ("Rücksicht nehmen auf", "nimmst du Rücksicht?"): ("С чем ты считаешься?", "С кем ты считаешься?"),
    ("Rücksicht nehmen auf", "nehmt ihr Rücksicht?"): ("С чем вы считаетесь?", "С кем вы считаетесь?"),
    # ── AUS + Dativ ──
    ("bestehen aus", "besteht das Team?"): ("Из чего состоит команда?", ""),
    ("bestehen aus", "besteht die Mischung?"): ("Из чего состоит смесь?", ""),
    ("entstehen aus", "entsteht es?"): ("Из чего это возникает?", ""),
    ("entstehen aus", "entsteht das?"): ("Из чего это возникает?", ""),
    ("folgen aus", "folgt es?"): ("Из чего это следует?", ""),
    ("folgen aus", "folgt das?"): ("Из чего это следует?", ""),
    # ── BEI + Dativ ──
    ("helfen bei", "hilfst du?"): ("В чём ты помогаешь?", ""),
    ("helfen bei", "helft ihr?"): ("В чём вы помогаете?", ""),
    ("sich bedanken bei", "bedankst du dich?"): ("", "Кого ты благодаришь?"),
    ("sich bedanken bei", "bedankt ihr euch?"): ("", "Кого вы благодарите?"),
    ("sich entschuldigen bei", "entschuldigst du dich?"): ("", "Перед кем ты извиняешься?"),
    ("sich entschuldigen bei", "entschuldigt ihr euch?"): ("", "Перед кем вы извиняетесь?"),
    ("bleiben bei", "bleibst du?"): ("Чего ты придерживаешься?", ""),
    ("bleiben bei", "bleibt ihr?"): ("Чего вы придерживаетесь?", ""),
    ("sich bewerben bei", "bewirbst du dich?"): ("", "Кому ты подаёшь заявку?"),
    ("sich bewerben bei", "bewerbt ihr euch?"): ("", "Кому вы подаёте заявку?"),
    # ── FÜR + Akkusativ ──
    ("sich interessieren für", "interessierst du dich?"): ("Чем ты интересуешься?", "Кем ты интересуешься?"),
    ("sich interessieren für", "interessiert ihr euch?"): ("Чем вы интересуетесь?", "Кем вы интересуетесь?"),
    ("danken für", "dankst du?"): ("За что ты благодаришь?", ""),
    ("danken für", "dankt ihr?"): ("За что вы благодарите?", ""),
    ("sich bedanken für", "bedankst du dich?"): ("За что ты благодаришь?", ""),
    ("sich bedanken für", "bedankt ihr euch?"): ("За что вы благодарите?", ""),
    ("sorgen für", "sorgst du?"): ("О чём ты заботишься?", "О ком ты заботишься?"),
    ("sorgen für", "sorgt ihr?"): ("О чём вы заботитесь?", "О ком вы заботитесь?"),
    ("sich entscheiden für", "entscheidest du dich?"): ("Что ты выбираешь?", "Кого ты выбираешь?"),
    ("sich entscheiden für", "entscheidet ihr euch?"): ("Что вы выбираете?", "Кого вы выбираете?"),
    ("sich engagieren für", "engagierst du dich?"): ("Чем ты активно занимаешься?", ""),
    ("sich engagieren für", "engagiert ihr euch?"): ("Чем вы активно занимаетесь?", ""),
    ("kämpfen für", "kämpfst du?"): ("За что ты борешься?", ""),
    ("kämpfen für", "kämpft ihr?"): ("За что вы боретесь?", ""),
    ("sich schämen für", "schämst du dich?"): ("За что тебе стыдно?", "За кого тебе стыдно?"),
    ("sich schämen für", "schämt ihr euch?"): ("За что вам стыдно?", "За кого вам стыдно?"),
    ("verantwortlich sein für", "bist du verantwortlich?"): ("За что ты отвечаешь?", "За кого ты отвечаешь?"),
    ("verantwortlich sein für", "seid ihr verantwortlich?"): ("За что вы отвечаете?", "За кого вы отвечаете?"),
    ("ausgeben für", "gibst du aus?"): ("На что ты тратишь деньги?", ""),
    ("ausgeben für", "gebt ihr aus?"): ("На что вы тратите деньги?", ""),
    # ── GEGEN + Akkusativ ──
    ("kämpfen gegen", "kämpfst du?"): ("Против чего ты борешься?", "Против кого ты борешься?"),
    ("kämpfen gegen", "kämpft ihr?"): ("Против чего вы боретесь?", "Против кого вы боретесь?"),
    ("sich wehren gegen", "wehrst du dich?"): ("От чего ты защищаешься?", "От кого ты защищаешься?"),
    ("sich wehren gegen", "wehrt ihr euch?"): ("От чего вы защищаетесь?", "От кого вы защищаетесь?"),
    ("verstoßen gegen", "verstößt du?"): ("Что ты нарушаешь?", ""),
    ("verstoßen gegen", "verstoßt ihr?"): ("Что вы нарушаете?", ""),
    ("stimmen gegen", "stimmst du?"): ("Против чего ты голосуешь?", "Против кого ты голосуешь?"),
    ("stimmen gegen", "stimmt ihr?"): ("Против чего вы голосуете?", "Против кого вы голосуете?"),
    # ── IN + Akkusativ ──
    ("sich verlieben in", "verliebst du dich?"): ("", "В кого ты влюбляешься?"),
    ("sich verlieben in", "verliebt ihr euch?"): ("", "В кого вы влюбляетесь?"),
    ("einwilligen in", "willigst du ein?"): ("На что ты соглашаешься?", ""),
    ("einwilligen in", "willigt ihr ein?"): ("На что вы соглашаетесь?", ""),
    ("geraten in", "gerätst du?"): ("Во что ты попадаешь?", ""),
    ("geraten in", "geratet ihr?"): ("Во что вы попадаете?", ""),
    ("sich einmischen in", "mischst du dich ein?"): ("Во что ты вмешиваешься?", ""),
    ("sich einmischen in", "mischt ihr euch ein?"): ("Во что вы вмешиваетесь?", ""),
    ("investieren in", "investierst du?"): ("Во что ты инвестируешь?", ""),
    ("investieren in", "investiert ihr?"): ("Во что вы инвестируете?", ""),
    # ── IN + Dativ ──
    ("bestehen in", "besteht es?"): ("В чём это заключается?", ""),
    ("bestehen in", "besteht das?"): ("В чём это заключается?", ""),
    # ── MIT + Dativ ──
    ("sprechen mit", "sprichst du?"): ("", "С кем ты говоришь?"),
    ("sprechen mit", "sprecht ihr?"): ("", "С кем вы говорите?"),
    ("reden mit", "redest du?"): ("", "С кем ты разговариваешь?"),
    ("reden mit", "redet ihr?"): ("", "С кем вы разговариваете?"),
    ("telefonieren mit", "telefonierst du?"): ("", "С кем ты говоришь по телефону?"),
    ("telefonieren mit", "telefoniert ihr?"): ("", "С кем вы говорите по телефону?"),
    ("sich treffen mit", "triffst du dich?"): ("", "С кем ты встречаешься?"),
    ("sich treffen mit", "trefft ihr euch?"): ("", "С кем вы встречаетесь?"),
    ("sich streiten mit", "streitest du dich?"): ("", "С кем ты ссоришься?"),
    ("sich streiten mit", "streitet ihr euch?"): ("", "С кем вы ссоритесь?"),
    ("sich unterhalten mit", "unterhältst du dich?"): ("", "С кем ты беседуешь?"),
    ("sich unterhalten mit", "unterhaltet ihr euch?"): ("", "С кем вы беседуете?"),
    ("sich verstehen mit", "verstehst du dich?"): ("", "С кем ты ладишь?"),
    ("sich verstehen mit", "versteht ihr euch?"): ("", "С кем вы ладите?"),
    ("verheiratet sein mit", "bist du verheiratet?"): ("", "С кем ты в браке?"),
    ("verheiratet sein mit", "seid ihr verheiratet?"): ("", "С кем вы в браке?"),
    ("anfangen mit", "fängst du an?"): ("С чего ты начинаешь?", ""),
    ("anfangen mit", "fangt ihr an?"): ("С чего вы начинаете?", ""),
    ("aufhören mit", "hörst du auf?"): ("Что ты прекращаешь?", ""),
    ("aufhören mit", "hört ihr auf?"): ("Что вы прекращаете?", ""),
    ("beginnen mit", "beginnst du?"): ("С чего ты начинаешь?", ""),
    ("beginnen mit", "beginnt ihr?"): ("С чего вы начинаете?", ""),
    ("zufrieden sein mit", "bist du zufrieden?"): ("Чем ты доволен?", "Кем ты доволен?"),
    ("zufrieden sein mit", "seid ihr zufrieden?"): ("Чем вы довольны?", "Кем вы довольны?"),
    ("einverstanden sein mit", "bist du einverstanden?"): ("С чем ты согласен?", "С кем ты согласен?"),
    ("einverstanden sein mit", "seid ihr einverstanden?"): ("С чем вы согласны?", "С кем вы согласны?"),
    ("übereinstimmen mit", "stimmst du überein?"): ("С чем ты согласен?", "С кем ты согласен?"),
    ("übereinstimmen mit", "stimmt ihr überein?"): ("С чем вы согласны?", "С кем вы согласны?"),
    # ── NACH + Dativ ──
    ("fragen nach", "fragst du?"): ("О чём ты спрашиваешь?", "О ком ты спрашиваешь?"),
    ("fragen nach", "fragt ihr?"): ("О чём вы спрашиваете?", "О ком вы спрашиваете?"),
    ("suchen nach", "suchst du?"): ("Что ты ищешь?", "Кого ты ищешь?"),
    ("suchen nach", "sucht ihr?"): ("Что вы ищете?", "Кого вы ищете?"),
    ("sich erkundigen nach", "erkundigst du dich?"): ("О чём ты справляешься?", "О ком ты справляешься?"),
    ("sich erkundigen nach", "erkundigt ihr euch?"): ("О чём вы справляетесь?", "О ком вы справляетесь?"),
    ("streben nach", "strebst du?"): ("К чему ты стремишься?", ""),
    ("streben nach", "strebt ihr?"): ("К чему вы стремитесь?", ""),
    ("sich sehnen nach", "sehnst du dich?"): ("По чему ты тоскуешь?", "По кому ты тоскуешь?"),
    ("sich sehnen nach", "sehnt ihr euch?"): ("По чему вы тоскуете?", "По кому вы тоскуете?"),
    ("greifen nach", "greifst du?"): ("За чем ты тянешься?", ""),
    ("greifen nach", "greift ihr?"): ("За чем вы тянетесь?", ""),
    ("klingen nach", "klingt es?"): ("На что это похоже?", ""),
    ("klingen nach", "klingt das?"): ("На что это похоже?", ""),
    # ── ÜBER + Akkusativ ──
    ("sprechen über", "sprichst du?"): ("О чём ты говоришь?", "О ком ты говоришь?"),
    ("sprechen über", "sprecht ihr?"): ("О чём вы говорите?", "О ком вы говорите?"),
    ("reden über", "redest du?"): ("О чём ты говоришь?", "О ком ты говоришь?"),
    ("reden über", "redet ihr?"): ("О чём вы говорите?", "О ком вы говорите?"),
    ("sich freuen über", "freust du dich?"): ("Чему ты радуешься?", "Кому ты радуешься?"),
    ("sich freuen über", "freut ihr euch so sehr?"): ("Чему вы так радуетесь?", "Кому вы так радуетесь?"),
    ("sich ärgern über", "ärgerst du dich?"): ("Из-за чего ты злишься?", "Из-за кого ты злишься?"),
    ("sich ärgern über", "ärgert ihr euch?"): ("Из-за чего вы злитесь?", "Из-за кого вы злитесь?"),
    ("sich aufregen über", "regst du dich auf?"): ("Из-за чего ты нервничаешь?", "Из-за кого ты нервничаешь?"),
    ("sich aufregen über", "regt ihr euch auf?"): ("Из-за чего вы нервничаете?", "Из-за кого вы нервничаете?"),
    ("schreiben über", "schreibst du?"): ("О чём ты пишешь?", "О ком ты пишешь?"),
    ("schreiben über", "schreibt ihr?"): ("О чём вы пишете?", "О ком вы пишете?"),
    ("sich informieren über", "informierst du dich?"): ("О чём ты узнаёшь?", "О ком ты узнаёшь?"),
    ("sich informieren über", "informiert ihr euch?"): ("О чём вы узнаёте?", "О ком вы узнаёте?"),
    ("lachen über", "lachst du?"): ("Над чем ты смеёшься?", "Над кем ты смеёшься?"),
    ("lachen über", "lacht ihr?"): ("Над чем вы смеётесь?", "Над кем вы смеётесь?"),
    ("sich wundern über", "wunderst du dich?"): ("Чему ты удивляешься?", "Кому ты удивляешься?"),
    ("sich wundern über", "wundert ihr euch?"): ("Чему вы удивляетесь?", "Кому вы удивляетесь?"),
    ("diskutieren über", "diskutierst du?"): ("Что ты обсуждаешь?", "Кого ты обсуждаешь?"),
    ("diskutieren über", "diskutiert ihr?"): ("Что вы обсуждаете?", "Кого вы обсуждаете?"),
    ("verfügen über", "verfügst du?"): ("Чем ты располагаешь?", ""),
    ("verfügen über", "verfügt ihr?"): ("Чем вы располагаете?", ""),
    ("klagen über", "klagst du?"): ("На что ты жалуешься?", ""),
    ("klagen über", "klagt ihr?"): ("На что вы жалуетесь?", ""),
    ("urteilen über", "urteilst du?"): ("О чём ты судишь?", "О ком ты судишь?"),
    ("urteilen über", "urteilt ihr?"): ("О чём вы судите?", "О ком вы судите?"),
    ("froh sein über", "bist du froh?"): ("Чему ты рад?", ""),
    ("froh sein über", "seid ihr froh?"): ("Чему вы рады?", ""),
    ("traurig sein über", "bist du traurig?"): ("Из-за чего ты грустишь?", "Из-за кого ты грустишь?"),
    ("traurig sein über", "seid ihr traurig?"): ("Из-за чего вы грустите?", "Из-за кого вы грустите?"),
    # ── UM + Akkusativ ──
    ("sich kümmern um", "kümmerst du dich?"): ("О чём ты заботишься?", "О ком ты заботишься?"),
    ("sich kümmern um", "kümmert ihr euch?"): ("О чём вы заботитесь?", "О ком вы заботитесь?"),
    ("bitten um", "bittest du?"): ("О чём ты просишь?", ""),
    ("bitten um", "bittet ihr?"): ("О чём вы просите?", ""),
    ("sich Sorgen machen um", "machst du dir Sorgen?"): ("О чём ты беспокоишься?", "О ком ты беспокоишься?"),
    ("sich Sorgen machen um", "macht ihr euch Sorgen?"): ("О чём вы беспокоитесь?", "О ком вы беспокоитесь?"),
    ("kämpfen um", "kämpfst du?"): ("За что ты борешься?", ""),
    ("kämpfen um", "kämpft ihr?"): ("За что вы боретесь?", ""),
    ("es geht um", "geht es?"): ("О чём речь?", ""),
    ("es geht um", "geht es hier?"): ("О чём здесь речь?", ""),
    ("es handelt sich um", "handelt es sich?"): ("О чём идёт речь?", ""),
    ("es handelt sich um", "handelt es sich hier?"): ("О чём здесь идёт речь?", ""),
    ("sich streiten um", "streitet ihr euch?"): ("Из-за чего вы ссоритесь?", ""),
    ("sich streiten um", "streiten sie sich?"): ("Из-за чего они ссорятся?", ""),
    ("beneiden um", "beneidest du ihn?"): ("Чему ты ему завидуешь?", ""),
    ("beneiden um", "beneidet ihr sie?"): ("Чему вы ей завидуете?", ""),
    ("trauern um", "trauerst du?"): ("О чём ты горюешь?", "О ком ты горюешь?"),
    ("trauern um", "trauert ihr?"): ("О чём вы горюете?", "О ком вы горюете?"),
    ("fürchten um", "fürchtest du?"): ("За что ты опасаешься?", ""),
    ("fürchten um", "fürchtet ihr?"): ("За что вы опасаетесь?", ""),
    # ── UNTER + Dativ ──
    ("verstehen unter", "verstehst du?"): ("Что ты под этим понимаешь?", ""),
    ("verstehen unter", "versteht ihr?"): ("Что вы под этим понимаете?", ""),
    # ── VON + Dativ ──
    ("träumen von", "träumst du?"): ("О чём ты мечтаешь?", "О ком ты мечтаешь?"),
    ("träumen von", "träumt ihr?"): ("О чём вы мечтаете?", "О ком вы мечтаете?"),
    ("erzählen von", "erzählst du?"): ("О чём ты рассказываешь?", "О ком ты рассказываешь?"),
    ("erzählen von", "erzählt ihr?"): ("О чём вы рассказываете?", "О ком вы рассказываете?"),
    ("abhängen von", "hängt es ab?"): ("От чего это зависит?", "От кого это зависит?"),
    ("abhängen von", "hängt das ab?"): ("От чего это зависит?", "От кого это зависит?"),
    ("sich verabschieden von", "verabschiedest du dich?"): ("", "С кем ты прощаешься?"),
    ("sich verabschieden von", "verabschiedet ihr euch?"): ("", "С кем вы прощаетесь?"),
    ("handeln von", "handelt es?"): ("О чём это?", ""),
    ("handeln von", "handelt das Buch?"): ("О чём эта книга?", ""),
    ("überzeugen von", "überzeugst du?"): ("В чём ты убеждаешь?", ""),
    ("überzeugen von", "überzeugt ihr?"): ("В чём вы убеждаете?", ""),
    ("sich ernähren von", "ernährst du dich?"): ("Чем ты питаешься?", ""),
    ("sich ernähren von", "ernährt ihr euch?"): ("Чем вы питаетесь?", ""),
    ("ausgehen von", "gehst du aus?"): ("Из чего ты исходишь?", ""),
    ("ausgehen von", "geht ihr aus?"): ("Из чего вы исходите?", ""),
    ("leben von", "lebst du?"): ("На что ты живёшь?", ""),
    ("leben von", "lebt ihr?"): ("На что вы живёте?", ""),
    ("halten von", "hältst du?"): ("О чём ты хорошего мнения?", "О ком ты хорошего мнения?"),
    ("halten von", "haltet ihr?"): ("О чём вы хорошего мнения?", "О ком вы хорошего мнения?"),
    # ── VOR + Dativ ──
    ("Angst haben vor", "hast du Angst?"): ("Чего ты боишься?", "Кого ты боишься?"),
    ("Angst haben vor", "habt ihr Angst?"): ("Чего вы боитесь?", "Кого вы боитесь?"),
    ("sich fürchten vor", "fürchtest du dich?"): ("Чего ты боишься?", "Кого ты боишься?"),
    ("sich fürchten vor", "fürchtet ihr euch?"): ("Чего вы боитесь?", "Кого вы боитесь?"),
    ("warnen vor", "warnst du?"): ("О чём ты предупреждаешь?", "О ком ты предупреждаешь?"),
    ("warnen vor", "warnt ihr?"): ("О чём вы предупреждаете?", "О ком вы предупреждаете?"),
    ("sich schützen vor", "schützt du dich?"): ("От чего ты защищаешься?", "От кого ты защищаешься?"),
    ("sich schützen vor", "schützt ihr euch?"): ("От чего вы защищаетесь?", "От кого вы защищаетесь?"),
    ("fliehen vor", "fliehst du?"): ("От чего ты бежишь?", "От кого ты бежишь?"),
    ("fliehen vor", "flieht ihr?"): ("От чего вы бежите?", "От кого вы бежите?"),
    ("sich verstecken vor", "versteckst du dich?"): ("От чего ты прячешься?", "От кого ты прячешься?"),
    ("sich verstecken vor", "versteckt ihr euch?"): ("От чего вы прячетесь?", "От кого вы прячетесь?"),
    ("Respekt haben vor", "hast du Respekt?"): ("К чему ты относишься с уважением?", "К кому ты относишься с уважением?"),
    ("Respekt haben vor", "habt ihr Respekt?"): ("К чему вы относитесь с уважением?", "К кому вы относитесь с уважением?"),
    ("sich ekeln vor", "ekelst du dich?"): ("Что тебе противно?", "Кто тебе противен?"),
    ("sich ekeln vor", "ekelt ihr euch?"): ("Что вам противно?", "Кто вам противен?"),
    ("zittern vor", "zitterst du?"): ("От чего ты дрожишь?", ""),
    ("zittern vor", "zittert ihr?"): ("От чего вы дрожите?", ""),
    # ── ZU + Dativ ──
    ("gehören zu", "gehört dieser Schlüssel?"): ("К чему относится этот ключ?", ""),
    ("gehören zu", "gehört dieses Zimmer?"): ("К чему относится эта комната?", ""),
    ("einladen zu", "lädst du ein?"): ("На что ты приглашаешь?", ""),
    ("einladen zu", "ladet ihr ein?"): ("На что вы приглашаете?", ""),
    ("gratulieren zu", "gratulierst du?"): ("С чем ты поздравляешь?", ""),
    ("gratulieren zu", "gratuliert ihr?"): ("С чем вы поздравляете?", ""),
    ("führen zu", "führt es?"): ("К чему это ведёт?", ""),
    ("führen zu", "führt das?"): ("К чему это ведёт?", ""),
    ("beitragen zu", "trägst du bei?"): ("Чему ты способствуешь?", ""),
    ("beitragen zu", "tragt ihr bei?"): ("Чему вы способствуете?", ""),
    ("sich entschließen zu", "entschließt du dich?"): ("На что ты решаешься?", ""),
    ("sich entschließen zu", "entschließt ihr euch?"): ("На что вы решаетесь?", ""),
    ("zwingen zu", "zwingst du ihn?"): ("К чему ты его принуждаешь?", ""),
    ("zwingen zu", "zwingt ihr sie?"): ("К чему вы её принуждаете?", ""),
    ("ermutigen zu", "ermutigst du ihn?"): ("К чему ты его побуждаешь?", ""),
    ("ermutigen zu", "ermutigt ihr sie?"): ("К чему вы её побуждаете?", ""),
    ("bereit sein zu", "bist du bereit?"): ("К чему ты готов?", ""),
    ("bereit sein zu", "seid ihr bereit?"): ("К чему вы готовы?", ""),
    ("Stellung nehmen zu", "nimmst du Stellung?"): ("О чём ты высказываешься?", ""),
    ("Stellung nehmen zu", "nehmt ihr Stellung?"): ("О чём вы высказываетесь?", ""),
}


def question_ru(lemma: str, frame: str, target: str) -> str:
    """Перевод вопроса. Нет перевода — пустая строка: выдумывать нельзя."""
    pair = QUESTION_RU.get((str(lemma or ""), str(frame or "")))
    if not pair:
        return ""
    return (pair[0] if target == "thing" else pair[1]).strip()
